import base64
import html
import json
import re

import streamlit as st
from openai import OpenAI

DEFAULT_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai"
GEMINI_API_ENABLE_URL = (
    "https://console.developers.google.com/apis/api/"
    "generativelanguage.googleapis.com/overview"
)
MODEL_SECRET_KEYS = ("model", "default_model")

LANGUAGE_OPTIONS = {"English": "en", "中文": "zh"}

TEXT = {
    "en": {
        "app_title": "Freshwise",
        "tagline": "See it. Cook it. Love it.",
        "subtitle": "Identify fridge ingredients, generate a recipe, and order what is missing.",
        "language": "Language",
        "settings": "Settings",
        "model_ready": "Model connected",
        "missing_secrets": "Missing Streamlit secrets: {items}",
        "goal": "Retail goal",
        "goal_options": [
            "Maximize basket value with relevant missing ingredients",
            "Prioritize fresh produce and dairy promotions",
            "Build a quick weeknight dinner plan",
            "Create a sponsored recipe placement",
        ],
        "scan": "Scan",
        "ingredients": "Ingredients",
        "recipe": "Recipe",
        "cart": "Cart",
        "camera": "Take a fridge photo",
        "recognize_photo": "Recognize Photo",
        "photo_hint": "On mobile, this opens the camera or photo picker.",
        "manual_input": "Manual ingredient input",
        "manual_placeholder": "tomatoes, spinach, eggs, cheese",
        "use_manual": "Use Manual Input",
        "use_demo": "Use Demo Ingredients",
        "detected": "Detected ingredients",
        "no_ingredients": "No ingredients yet. Take a photo or enter ingredients manually.",
        "no_recipe": "No recipes yet. Scan or enter ingredients, then generate recipes.",
        "no_cart": "No cart yet. Generate recipes and choose one to see missing ingredients.",
        "add_ingredient": "Add ingredient",
        "add": "Add",
        "remove": "Remove",
        "generate_recipe": "Generate Recipe",
        "regenerate": "Regenerate Recipe",
        "recipe_options": "Recipe options",
        "use_this_recipe": "Use this recipe",
        "current_recipe": "Current recipe",
        "model_generating": "Calling the configured multimodal model...",
        "model_recognizing": "Recognizing ingredients with the configured multimodal model...",
        "fallback_recipe": "Using local demo fallback because the model call was unavailable.",
        "fallback_photo": "Photo recognition needs a working multimodal model. Please confirm ingredients manually.",
        "generated_by_model": "Generated by the configured model.",
        "recognized_by_model": "Recognized by the configured model.",
        "meal": "Meal",
        "why": "Why this works",
        "chef_note": "Chef's inner monologue",
        "chef_note_hint": "A short, user-facing note about why this recipe direction makes sense.",
        "uses": "Uses",
        "missing": "Missing",
        "steps": "Steps",
        "recommended_products": "Recommended products",
        "qty": "Qty",
        "subtotal": "Subtotal",
        "delivery": "Delivery",
        "total": "Total",
        "clear_cart": "Clear cart",
        "reset_qty": "Reset quantities",
        "place_order": "Place mock order",
        "order_success": "Mock order placed",
        "need_ingredients": "Add at least one ingredient first.",
        "all_set": "All set",
        "photo_recognized_review": "Photo recognized. Please review the ingredients below.",
        "ingredients_updated": "Ingredients updated.",
        "recognized_results": "Recognized results",
        "local_demo": "Local demo",
    },
    "zh": {
        "app_title": "Freshwise",
        "tagline": "看見食材，做成料理，喜歡上晚餐。",
        "subtitle": "辨識冰箱食材、生成食譜，並把缺少的食材加入購物車。",
        "language": "語言",
        "settings": "設定",
        "model_ready": "模型已連線",
        "missing_secrets": "缺少 Streamlit secrets：{items}",
        "goal": "零售目標",
        "goal_options": [
            "用相關缺少食材提高購物籃金額",
            "優先推動生鮮與乳製品促銷",
            "建立快速週間晚餐方案",
            "建立贊助食譜版位",
        ],
        "scan": "掃描",
        "ingredients": "食材",
        "recipe": "食譜",
        "cart": "購物車",
        "camera": "拍攝冰箱照片",
        "recognize_photo": "辨識照片",
        "photo_hint": "手機上會開啟相機或相簿。",
        "manual_input": "手動輸入食材",
        "manual_placeholder": "番茄、菠菜、雞蛋、起司",
        "use_manual": "使用手動輸入",
        "use_demo": "使用範例食材",
        "detected": "已辨識食材",
        "no_ingredients": "目前沒有食材。請拍照或手動輸入。",
        "no_recipe": "目前還沒有食譜。請先拍照或輸入食材，再生成食譜。",
        "no_cart": "目前還沒有購物車。請先生成食譜並選擇一道料理。",
        "add_ingredient": "新增食材",
        "add": "新增",
        "remove": "移除",
        "generate_recipe": "生成食譜",
        "regenerate": "重新生成食譜",
        "recipe_options": "食譜選項",
        "use_this_recipe": "使用這道料理",
        "current_recipe": "目前料理",
        "model_generating": "正在呼叫設定的多模態模型...",
        "model_recognizing": "正在用設定的多模態模型辨識食材...",
        "fallback_recipe": "模型呼叫不可用，已改用本地 demo fallback。",
        "fallback_photo": "照片辨識需要可用的多模態模型，請手動確認食材。",
        "generated_by_model": "已由設定模型生成。",
        "recognized_by_model": "已由設定模型辨識。",
        "meal": "餐點",
        "why": "推薦原因",
        "chef_note": "大廚內心獨白",
        "chef_note_hint": "用給使用者看的方式，說明這道料理為什麼適合目前食材。",
        "uses": "使用食材",
        "missing": "缺少食材",
        "steps": "料理步驟",
        "recommended_products": "推薦商品",
        "qty": "數量",
        "subtotal": "小計",
        "delivery": "配送費",
        "total": "總計",
        "clear_cart": "清空購物車",
        "reset_qty": "重設數量",
        "place_order": "送出模擬訂單",
        "order_success": "模擬訂單已送出",
        "need_ingredients": "請至少加入一項食材。",
        "all_set": "完成",
        "photo_recognized_review": "照片已辨識，請確認下方食材。",
        "ingredients_updated": "食材已更新。",
        "recognized_results": "辨識結果",
        "local_demo": "本地範例",
    },
}

CATALOG = [
    {
        "name_en": "Heavy Cream",
        "name_zh": "鮮奶油",
        "category_en": "Dairy",
        "category_zh": "乳製品",
        "price": 2.49,
        "reason_en": "Makes tomato sauce smooth and rich.",
        "reason_zh": "讓番茄醬汁更滑順濃郁。",
    },
    {
        "name_en": "Parmesan Cheese",
        "name_zh": "帕瑪森起司",
        "category_en": "Dairy",
        "category_zh": "乳製品",
        "price": 2.99,
        "reason_en": "Adds a nutty, salty finish.",
        "reason_zh": "增加鹹香與堅果風味。",
    },
    {
        "name_en": "Fresh Basil",
        "name_zh": "新鮮羅勒",
        "category_en": "Herbs",
        "category_zh": "香草",
        "price": 1.79,
        "reason_en": "Brings a fresh green lift.",
        "reason_zh": "讓料理更清新有層次。",
    },
    {
        "name_en": "Garlic",
        "name_zh": "大蒜",
        "category_en": "Produce",
        "category_zh": "蔬果",
        "price": 0.89,
        "reason_en": "Builds the savory base.",
        "reason_zh": "建立料理的鹹香底味。",
    },
    {
        "name_en": "Pasta",
        "name_zh": "義大利麵",
        "category_en": "Pantry",
        "category_zh": "乾貨",
        "price": 1.99,
        "reason_en": "Turns fridge odds and ends into dinner.",
        "reason_zh": "把冰箱剩餘食材變成完整晚餐。",
    },
    {
        "name_en": "Cherry Tomatoes",
        "name_zh": "小番茄",
        "category_en": "Produce",
        "category_zh": "蔬果",
        "price": 3.49,
        "reason_en": "Cooks down into a sweet quick sauce.",
        "reason_zh": "能快速煮出清甜醬汁。",
    },
]

DEMO_INGREDIENTS = {
    "en": "tomatoes, spinach, eggs, cheese",
    "zh": "番茄、菠菜、雞蛋、起司",
}

FALLBACK_PLAN = {
    "en": {
        "meal_title": "Creamy Tomato Pasta",
        "reasoning_summary": "Use tomatoes and spinach as the fresh base, then add cream, parmesan, basil, and pasta to complete a fast dinner.",
        "chef_note": "I would lean into the tomatoes first, then use spinach for freshness and a creamy finish to make the dish feel complete.",
        "owned_ingredients": ["Tomatoes", "Spinach", "Cheese", "Eggs"],
        "missing_items": ["Heavy Cream", "Parmesan Cheese", "Fresh Basil"],
        "recommended_products": [
            {"name": "Heavy Cream", "reason": "Makes the sauce smooth.", "estimated_price": 2.49},
            {"name": "Parmesan Cheese", "reason": "Adds salty depth.", "estimated_price": 2.99},
            {"name": "Fresh Basil", "reason": "Finishes the dish fresh.", "estimated_price": 1.79},
        ],
        "recipe_steps": [
            "Boil pasta until al dente.",
            "Simmer tomatoes with garlic and a splash of cream.",
            "Fold in spinach, pasta, parmesan, and torn basil.",
        ],
        "cart_summary": {"item_count": 3, "estimated_total": 7.27},
    },
    "zh": {
        "meal_title": "奶油番茄義大利麵",
        "reasoning_summary": "用番茄與菠菜當新鮮基底，再補上鮮奶油、帕瑪森起司、羅勒與義大利麵，就能完成快速晚餐。",
        "chef_note": "我會先把番茄的酸甜煮出來，再用菠菜補清爽感，最後用奶油與起司把它收成一盤完整晚餐。",
        "owned_ingredients": ["番茄", "菠菜", "起司", "雞蛋"],
        "missing_items": ["鮮奶油", "帕瑪森起司", "新鮮羅勒"],
        "recommended_products": [
            {"name": "鮮奶油", "reason": "讓醬汁更滑順。", "estimated_price": 2.49},
            {"name": "帕瑪森起司", "reason": "增加鹹香深度。", "estimated_price": 2.99},
            {"name": "新鮮羅勒", "reason": "讓料理更清新。", "estimated_price": 1.79},
        ],
        "recipe_steps": [
            "將義大利麵煮到彈牙。",
            "用番茄、大蒜與少量鮮奶油煮成醬汁。",
            "拌入菠菜、義大利麵、起司與羅勒。",
        ],
        "cart_summary": {"item_count": 3, "estimated_total": 7.27},
    },
}

FALLBACK_RECIPE_VARIANTS = {
    "en": [
        {
            "meal_title": "Creamy Tomato Pasta",
            "reasoning_summary": "Use tomatoes and spinach as the fresh base, then add cream, parmesan, basil, and pasta to complete a fast dinner.",
            "chef_note": "I would lean into the tomatoes first, then use spinach for freshness and a creamy finish to make the dish feel complete.",
            "missing_items": ["Heavy Cream", "Parmesan Cheese", "Fresh Basil"],
            "recommended_products": [
                {"name": "Heavy Cream", "reason": "Makes the sauce smooth.", "estimated_price": 2.49},
                {"name": "Parmesan Cheese", "reason": "Adds salty depth.", "estimated_price": 2.99},
                {"name": "Fresh Basil", "reason": "Finishes the dish fresh.", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "Boil pasta until al dente.",
                "Simmer tomatoes with garlic and a splash of cream.",
                "Fold in spinach, pasta, parmesan, and torn basil.",
            ],
        },
        {
            "meal_title": "Spinach Cheese Omelet",
            "reasoning_summary": "Eggs and spinach become a fast protein-rich meal, with cheese for body and tomatoes for brightness.",
            "chef_note": "This is the quickest path when the fridge already has eggs: keep the center soft, then use tomatoes to wake it up.",
            "missing_items": ["Cherry Tomatoes", "Fresh Basil"],
            "recommended_products": [
                {"name": "Cherry Tomatoes", "reason": "Adds a juicy side.", "estimated_price": 3.49},
                {"name": "Fresh Basil", "reason": "Brightens the eggs.", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "Whisk eggs with a pinch of salt.",
                "Wilt spinach in a warm pan.",
                "Add eggs and cheese, fold gently, and serve with tomatoes and basil.",
            ],
        },
        {
            "meal_title": "Tomato Spinach Grain Bowl",
            "reasoning_summary": "Turn the ingredients into a flexible bowl by adding a grain base and a bright dressing.",
            "chef_note": "I would make this when you want something lighter than pasta but still complete enough to feel like dinner.",
            "missing_items": ["Pasta", "Fresh Basil"],
            "recommended_products": [
                {"name": "Pasta", "reason": "Works as the hearty base.", "estimated_price": 1.99},
                {"name": "Fresh Basil", "reason": "Adds a fresh finish.", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "Cook the grain or pasta base.",
                "Warm tomatoes until they soften and release juice.",
                "Toss with spinach, cheese, basil, and a drizzle of oil.",
            ],
        },
    ],
    "zh": [
        {
            "meal_title": "奶油番茄義大利麵",
            "reasoning_summary": "用番茄與菠菜當新鮮基底，再補上鮮奶油、帕瑪森起司、羅勒與義大利麵，就能完成快速晚餐。",
            "chef_note": "我會先把番茄的酸甜煮出來，再用菠菜補清爽感，最後用奶油與起司把它收成一盤完整晚餐。",
            "missing_items": ["鮮奶油", "帕瑪森起司", "新鮮羅勒"],
            "recommended_products": [
                {"name": "鮮奶油", "reason": "讓醬汁更滑順。", "estimated_price": 2.49},
                {"name": "帕瑪森起司", "reason": "增加鹹香層次。", "estimated_price": 2.99},
                {"name": "新鮮羅勒", "reason": "收尾更清爽。", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "將義大利麵煮到彈牙。",
                "把番茄與蒜炒軟，加入少量鮮奶油。",
                "拌入菠菜、義大利麵、起司與羅勒。",
            ],
        },
        {
            "meal_title": "菠菜起司歐姆蛋",
            "reasoning_summary": "雞蛋、菠菜與起司可以快速變成高蛋白餐點，再用番茄增加清爽酸甜。",
            "chef_note": "如果冰箱裡已經有蛋，我會走最快的路線：蛋保持柔嫩，番茄負責把味道點亮。",
            "missing_items": ["小番茄", "新鮮羅勒"],
            "recommended_products": [
                {"name": "小番茄", "reason": "做成多汁配菜。", "estimated_price": 3.49},
                {"name": "新鮮羅勒", "reason": "讓蛋香更清新。", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "雞蛋加鹽打散。",
                "菠菜下鍋炒軟。",
                "倒入蛋液與起司，摺成歐姆蛋，搭配番茄與羅勒。",
            ],
        },
        {
            "meal_title": "番茄菠菜溫沙拉碗",
            "reasoning_summary": "把現有食材做成清爽碗餐，補上一個主食基底與香草就能更完整。",
            "chef_note": "想吃得比義大利麵輕一點時，我會選這道；它簡單，但仍然像一份完整晚餐。",
            "missing_items": ["義大利麵", "新鮮羅勒"],
            "recommended_products": [
                {"name": "義大利麵", "reason": "作為飽足主食。", "estimated_price": 1.99},
                {"name": "新鮮羅勒", "reason": "增加清香。", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "煮好主食基底。",
                "番茄加熱到釋出汁水。",
                "拌入菠菜、起司、羅勒與少量橄欖油。",
            ],
        },
    ],
}

st.set_page_config(
    page_title="Freshwise",
    page_icon="FW",
    layout="centered",
    initial_sidebar_state="collapsed",
)


def lang():
    return st.session_state.get("language", "en")


def tr(key, **kwargs):
    value = TEXT[lang()][key]
    return value.format(**kwargs) if kwargs else value


def money(value):
    return f"${float(value or 0):.2f}"


def css():
    st.html(
        """
        <style>
        :root {
            --fw-ink: #123624;
            --fw-ink-strong: #0b2418;
            --fw-muted: #40573d;
            --fw-subtle: #586b51;
            --fw-surface: #fffdf7;
            --fw-surface-strong: #fbf8ee;
            --fw-surface-soft: #eef8e6;
            --fw-border: rgba(22, 63, 39, .18);
            --fw-primary: #1f6f38;
            --fw-primary-dark: #164f2a;
        }
        .stApp {
            background:
                radial-gradient(circle at 16% 3%, rgba(186, 217, 125, .35), transparent 280px),
                linear-gradient(135deg, #fffdf7 0%, #f3efde 100%);
            color: var(--fw-ink);
        }
        .stApp,
        .stApp p,
        .stApp li,
        .stApp label,
        .stApp span,
        .stApp div[data-testid="stMarkdownContainer"],
        .stApp div[data-testid="stMarkdownContainer"] p,
        .stApp div[data-testid="stCaptionContainer"],
        .stApp div[data-testid="stMetric"] label,
        .stApp div[data-testid="stMetric"] [data-testid="stMetricValue"],
        .stApp div[data-testid="stMetric"] [data-testid="stMetricLabel"] {
            color: var(--fw-ink);
        }
        .stApp h1,
        .stApp h2,
        .stApp h3,
        .stApp h4,
        .stApp h5,
        .stApp h6 {
            color: var(--fw-ink-strong);
        }
        header[data-testid="stHeader"],
        .stAppHeader,
        [data-testid="stToolbar"],
        [data-testid="stDecoration"] {
            display: none !important;
            visibility: hidden !important;
            height: 0 !important;
            min-height: 0 !important;
            pointer-events: none !important;
        }
        .block-container {
            max-width: 560px;
            padding: 14px 14px 34px;
        }
        [role="radiogroup"] {
            display: inline-flex;
            gap: 6px;
            padding: 6px;
            margin-bottom: 10px;
            border: 1px solid var(--fw-border);
            border-radius: 999px;
            background: #e6f0dc;
        }
        [role="radiogroup"] label {
            min-height: 34px;
            padding: 6px 10px;
            border-radius: 999px;
            color: var(--fw-ink);
        }
        [role="radiogroup"] label:has(input:checked) {
            background: var(--fw-surface);
            box-shadow: 0 5px 12px rgba(34, 68, 38, .12);
        }
        .hero {
            padding: 20px 18px;
            border: 1px solid var(--fw-border);
            border-radius: 26px;
            background: rgba(255, 253, 247, .96);
            box-shadow: 0 18px 40px rgba(34, 68, 38, .10);
        }
        .brand {
            margin: 0 0 4px;
            color: var(--fw-primary-dark);
            font-size: 34px;
            font-weight: 900;
            letter-spacing: 0;
        }
        .tagline {
            margin: 0;
            color: var(--fw-muted);
            font-size: 15px;
            line-height: 1.5;
        }
        .card {
            padding: 16px;
            border: 1px solid var(--fw-border);
            border-radius: 22px;
            background: rgba(255, 253, 247, .96);
            box-shadow: 0 10px 24px rgba(34, 68, 38, .08);
        }
        .recipe-option {
            margin: 10px 0;
            padding: 12px 14px;
            border: 1px solid var(--fw-border);
            border-radius: 18px;
            background: var(--fw-surface);
        }
        .recipe-option.selected {
            border: 2px solid var(--fw-primary);
            background: var(--fw-surface-soft);
            box-shadow: 0 12px 24px rgba(47, 123, 63, .16);
        }
        .recipe-option-title {
            margin: 0 0 4px;
            color: var(--fw-ink-strong);
            font-weight: 900;
        }
        .recipe-option-copy {
            margin: 0;
            color: var(--fw-muted);
            font-size: 14px;
            line-height: 1.45;
        }
        .ingredient-strip {
            margin: 0 0 14px;
            padding: 12px;
            border: 1px solid var(--fw-border);
            border-radius: 18px;
            background: rgba(255, 253, 247, .78);
        }
        .ingredient-strip-title {
            margin: 0 0 8px;
            color: var(--fw-muted);
            font-size: 13px;
            font-weight: 800;
        }
        .ingredient-chip-row {
            display: flex;
            flex-wrap: wrap;
            gap: 7px;
        }
        .ingredient-chip {
            display: inline-flex;
            align-items: center;
            min-height: 30px;
            padding: 5px 10px;
            border: 1px solid rgba(31, 111, 56, .24);
            border-radius: 999px;
            background: #eaf5df;
            color: var(--fw-ink-strong);
            font-size: 13px;
            font-weight: 800;
            line-height: 1.2;
        }
        div[data-testid="stTabs"] {
            margin-top: 16px;
        }
        div[data-testid="stTabs"] div[role="tablist"] {
            display: grid;
            grid-template-columns: repeat(5, minmax(0, 1fr));
            gap: 6px;
            padding: 6px;
            border: 1px solid var(--fw-border);
            border-radius: 22px;
            background: #e6f0dc;
            box-shadow: inset 0 1px 0 rgba(255, 255, 255, .8);
        }
        div[data-testid="stTabs"] button[role="tab"] {
            min-height: 44px;
            padding: 8px 4px;
            border-radius: 16px;
            color: var(--fw-ink);
            font-weight: 800;
            border: 1px solid transparent;
            background: transparent;
        }
        div[data-testid="stTabs"] button[aria-selected="true"] {
            color: var(--fw-ink-strong);
            border-color: rgba(31, 111, 56, .35);
            background: var(--fw-surface);
            box-shadow: 0 8px 18px rgba(34, 68, 38, .10);
        }
        div[data-testid="stTabs"] [data-baseweb="tab-highlight"] {
            display: none;
        }
        @media (max-width: 430px) {
            div[data-testid="stTabs"] button[role="tab"] {
                font-size: 13px;
            }
        }
        .stButton > button {
            border-radius: 999px;
            min-height: 48px;
            font-weight: 800;
            color: var(--fw-ink-strong);
            border-color: rgba(31, 111, 56, .28);
            background: var(--fw-surface);
        }
        .stButton > button * {
            color: inherit;
        }
        .stButton > button[kind="primary"],
        .stButton > button[data-testid="baseButton-primary"] {
            color: #fffdf7;
            border-color: var(--fw-primary-dark);
            background: var(--fw-primary);
        }
        .stButton > button:disabled,
        button[data-testid="stCameraInputButton"]:disabled,
        button[data-testid="baseButton-primary"]:disabled,
        button[data-testid="baseButton-secondary"]:disabled {
            color: var(--fw-muted);
            border-color: rgba(22, 63, 39, .22);
            background: #f7f3e8;
            opacity: 1;
        }
        .stTextArea textarea,
        .stTextInput input,
        div[data-baseweb="select"] > div {
            color: var(--fw-ink-strong);
            border-color: var(--fw-border);
            background: var(--fw-surface);
        }
        .stTextArea textarea::placeholder,
        .stTextInput input::placeholder {
            color: var(--fw-subtle);
            opacity: 1;
        }
        [data-testid="stMetric"] {
            border: 1px solid var(--fw-border);
            border-radius: 18px;
            padding: 10px;
            background: rgba(255, 253, 247, .96);
        }
        [data-testid="stExpander"] {
            border-color: var(--fw-border);
            background: rgba(255, 253, 247, .9);
        }
        a {
            color: var(--fw-primary-dark);
        }
        </style>
        """
    )


def read_runtime_config():
    try:
        api_key = st.secrets.get("api_key")
        model = next((st.secrets.get(key) for key in MODEL_SECRET_KEYS if st.secrets.get(key)), None)
    except Exception:
        return {"ready": False, "api_key": "", "model": "", "error": tr("missing_secrets", items="api_key, default_model")}

    missing = []
    if not api_key:
        missing.append("api_key")
    if not model:
        missing.append("default_model/model")
    if missing:
        return {"ready": False, "api_key": "", "model": "", "error": tr("missing_secrets", items=", ".join(missing))}
    return {"ready": True, "api_key": api_key, "model": model, "error": ""}


def parse_ingredients(text):
    parts = re.split(r"[,，、\n]+", text or "")
    return [part.strip().title() if lang() == "en" else part.strip() for part in parts if part.strip()]


def catalog_prompt():
    suffix = lang()
    rows = []
    for item in CATALOG:
        rows.append(
            f"- {item[f'name_{suffix}']} / {item[f'category_{suffix}']} / "
            f"${item['price']:.2f} / {item[f'reason_{suffix}']}"
        )
    return "\n".join(rows)


def clean_response(raw):
    raw = re.sub(r"<thought>.*?</thought>", "", raw or "", flags=re.DOTALL | re.IGNORECASE)
    raw = re.sub(r"```[a-zA-Z]*\n?|```", "", raw)
    return raw.strip()


def extract_json(raw):
    cleaned = clean_response(raw)
    match = re.search(r"(\{.*\})", cleaned, re.DOTALL)
    if not match:
        raise ValueError("No JSON object found.")
    return json.loads(match.group(1))


def generate_plan(api_key, model, ingredients, business_goal):
    output_language = "Traditional Chinese" if lang() == "zh" else "English"
    system_prompt = f"""
You are Freshwise, a multimodal meal-to-cart engine for a grocery app.
Create exactly three practical dinner recommendations from the user's ingredients and the retailer promotion catalog.
Recommend missing items only when useful for the recipe.
Output language: {output_language}.
Business goal: {business_goal}

Promotion catalog:
{catalog_prompt()}

Return only valid JSON with this shape:
{{
  "recipes": [
    {{
      "meal_title": "string",
      "reasoning_summary": "string",
      "chef_note": "string",
      "owned_ingredients": ["string"],
      "missing_items": ["string"],
      "recommended_products": [
        {{"name": "string", "reason": "string", "estimated_price": 0}}
      ],
      "recipe_steps": ["string"],
      "cart_summary": {{"item_count": 0, "estimated_total": 0}}
    }}
  ]
}}
"""
    client = OpenAI(api_key=api_key, base_url=DEFAULT_BASE_URL)
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Ingredients: {', '.join(ingredients)}"},
        ],
        response_format={"type": "json_object"},
    )
    data = extract_json(response.choices[0].message.content)
    if isinstance(data.get("recipes"), list):
        data["recipes"] = data["recipes"][:3]
    elif not isinstance(data.get("recommended_products"), list):
        raise ValueError("Model JSON missing recipes.")
    return data


def recognize_ingredients(api_key, model, image_bytes):
    output_language = "Traditional Chinese" if lang() == "zh" else "English"
    encoded = base64.b64encode(image_bytes).decode("ascii")
    client = OpenAI(api_key=api_key, base_url=DEFAULT_BASE_URL)
    response = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": (
                    "You identify visible food ingredients from fridge or kitchen photos. "
                    f"Return only JSON in {output_language}: "
                    '{"ingredients":["ingredient name"]}. Do not include non-food objects.'
                ),
            },
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": "Identify the visible food ingredients."},
                    {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{encoded}"}},
                ],
            },
        ],
        response_format={"type": "json_object"},
    )
    data = extract_json(response.choices[0].message.content)
    ingredients = data.get("ingredients", [])
    if not isinstance(ingredients, list):
        raise ValueError("Model JSON missing ingredients.")
    return [str(item).strip() for item in ingredients if str(item).strip()]


def fallback_plan(ingredients):
    owned = ingredients or FALLBACK_PLAN[lang()]["owned_ingredients"]
    recipes = []
    for variant in FALLBACK_RECIPE_VARIANTS[lang()]:
        recipe = {**FALLBACK_PLAN[lang()], **variant}
        recipe["owned_ingredients"] = owned
        recipes.append(recipe)
    return {"recipes": recipes}


def recipe_options(plan):
    if not plan:
        return []
    raw = plan
    recipes = raw.get("recipes") if isinstance(raw, dict) else None
    if not isinstance(recipes, list) or not recipes:
        recipes = [raw]
    normalized = []
    base = FALLBACK_PLAN[lang()]
    for recipe in recipes[:3]:
        merged = {**base, **(recipe or {})}
        merged["owned_ingredients"] = merged.get("owned_ingredients") or base["owned_ingredients"]
        merged["missing_items"] = merged.get("missing_items") or base["missing_items"]
        merged["recommended_products"] = merged.get("recommended_products") or base["recommended_products"]
        merged["recipe_steps"] = merged.get("recipe_steps") or base["recipe_steps"]
        merged["chef_note"] = merged.get("chef_note") or merged.get("reasoning_summary") or base.get("chef_note", "")
        normalized.append(merged)
    return normalized


def normalize_plan(plan):
    recipes = recipe_options(plan)
    if not recipes:
        return {}
    selected = min(st.session_state.get("selected_recipe_index", 0), len(recipes) - 1)
    st.session_state["selected_recipe_index"] = selected
    return recipes[selected]


def sync_cart(plan):
    cart = st.session_state.setdefault("cart_quantities", {})
    product_names = [product.get("name", "") for product in plan["recommended_products"]]
    for name in product_names:
        cart.setdefault(name, 1)
    for name in list(cart):
        if name not in product_names:
            del cart[name]


def cart_totals(plan):
    subtotal = 0.0
    count = 0
    quantities = st.session_state.setdefault("cart_quantities", {})
    for product in plan["recommended_products"]:
        name = product.get("name", "")
        qty = int(quantities.get(name, 1))
        subtotal += float(product.get("estimated_price", 0) or 0) * qty
        count += qty
    return round(subtotal, 2), count


def set_demo():
    ingredients = parse_ingredients(DEMO_INGREDIENTS[lang()])
    st.session_state["ingredients"] = ingredients
    st.session_state["manual_text"] = DEMO_INGREDIENTS[lang()]
    st.session_state["plan"] = fallback_plan(ingredients)
    st.session_state["selected_recipe_index"] = 0
    st.session_state["status"] = tr("local_demo")


def ingredients_to_text(ingredients):
    separator = ", " if lang() == "en" else "、"
    return separator.join(ingredients)


def render_selected_ingredients():
    ingredients = st.session_state.get("ingredients", [])
    if not ingredients:
        st.info(tr("no_ingredients"))
        return
    chips = "".join(
        f'<span class="ingredient-chip">{html.escape(str(ingredient))}</span>'
        for ingredient in ingredients
    )
    st.html(
        f"""
        <div class="ingredient-strip">
            <p class="ingredient-strip-title">{html.escape(tr("ingredients"))}</p>
            <div class="ingredient-chip-row">{chips}</div>
        </div>
        """
    )


def format_model_error(exc):
    detail = str(exc)
    if "SERVICE_DISABLED" in detail or "Gemini API has not been used" in detail:
        return (
            "Gemini API is disabled for this Google Cloud project. Enable it here: "
            f"{GEMINI_API_ENABLE_URL}. If you just enabled it, wait a few minutes and retry."
        )
    if "API_KEY_SERVICE_BLOCKED" in detail or "Requests to this API" in detail:
        return (
            "This API key is blocking Gemini requests. In Google Cloud Console, open the "
            "API key restrictions and allow Generative Language API "
            "(generativelanguage.googleapis.com), or temporarily set API restrictions to "
            "unrestricted while testing."
        )
    if "PERMISSION_DENIED" in detail or "Error code: 403" in detail:
        return (
            "Gemini returned 403 PERMISSION_DENIED. Check that the API key belongs to a "
            "project with Gemini API enabled and that the key is allowed to call it."
        )
    return detail


def generate_recipe(runtime_config, business_goal):
    ingredients = st.session_state.get("ingredients", [])
    if not ingredients:
        st.warning(tr("need_ingredients"))
        return
    if runtime_config["ready"]:
        try:
            with st.spinner(tr("model_generating")):
                st.session_state["plan"] = generate_plan(
                    runtime_config["api_key"],
                    runtime_config["model"],
                    ingredients,
                    business_goal,
                )
                st.session_state["selected_recipe_index"] = 0
            st.session_state["status"] = tr("generated_by_model")
            return
        except Exception as exc:
            st.warning(f"{tr('fallback_recipe')} ({format_model_error(exc)})")
    else:
        st.warning(runtime_config["error"])
    st.session_state["plan"] = fallback_plan(ingredients)
    st.session_state["selected_recipe_index"] = 0
    st.session_state["status"] = tr("fallback_recipe")


def render_header():
    st.html(
        f"""
        <div class="hero">
            <h1 class="brand">{tr("app_title")}</h1>
            <p class="tagline"><strong>{tr("tagline")}</strong><br>{tr("subtitle")}</p>
        </div>
        """
    )


def render_scan(runtime_config):
    st.subheader(tr("scan"))
    photo = st.camera_input(tr("camera"), help=tr("photo_hint"))
    if st.button(tr("recognize_photo"), type="primary", use_container_width=True, disabled=photo is None):
        if not runtime_config["ready"]:
            st.warning(tr("fallback_photo"))
        else:
            try:
                with st.spinner(tr("model_recognizing")):
                    ingredients = recognize_ingredients(runtime_config["api_key"], runtime_config["model"], photo.getvalue())
                st.session_state["ingredients"] = ingredients
                st.session_state["manual_text"] = ingredients_to_text(ingredients)
                st.session_state["plan"] = None
                st.session_state["selected_recipe_index"] = 0
                st.session_state["status"] = tr("recognized_by_model")
                st.success(tr("photo_recognized_review"))
            except Exception as exc:
                st.warning(f"{tr('fallback_photo')} ({format_model_error(exc)})")

    st.markdown("---")
    manual = st.text_area(
        tr("manual_input"),
        placeholder=tr("manual_placeholder"),
        key="manual_text",
    )
    col1, col2 = st.columns(2)
    if col1.button(tr("use_manual"), use_container_width=True):
        ingredients = parse_ingredients(manual)
        if ingredients:
            st.session_state["ingredients"] = ingredients
            st.session_state["plan"] = None
            st.session_state["selected_recipe_index"] = 0
            st.success(tr("ingredients_updated"))
        else:
            st.warning(tr("need_ingredients"))
    col2.button(tr("use_demo"), use_container_width=True, on_click=set_demo)


def render_ingredients():
    st.subheader(tr("detected"))
    ingredients = st.session_state.get("ingredients", [])
    if not ingredients:
        st.info(tr("no_ingredients"))
    for index, ingredient in enumerate(list(ingredients)):
        col1, col2 = st.columns([3, 1])
        col1.write(f"**{ingredient}**")
        if col2.button(tr("remove"), key=f"remove_{index}", use_container_width=True):
            ingredients.pop(index)
            st.session_state["ingredients"] = ingredients
            st.session_state["plan"] = None
            st.session_state["selected_recipe_index"] = 0
            st.rerun()

    new_item = st.text_input(tr("add_ingredient"), key="new_ingredient")
    if st.button(tr("add"), use_container_width=True):
        value = new_item.strip().title() if lang() == "en" else new_item.strip()
        if value:
            ingredients.append(value)
            st.session_state["ingredients"] = ingredients
            st.session_state["plan"] = None
            st.session_state["selected_recipe_index"] = 0
            st.rerun()


def render_recipe(runtime_config, business_goal):
    st.subheader(tr("recipe"))
    render_selected_ingredients()
    if st.button(tr("generate_recipe"), type="primary", use_container_width=True):
        generate_recipe(runtime_config, business_goal)

    recipes = recipe_options(st.session_state.get("plan"))
    if not recipes:
        st.info(tr("no_recipe"))
        return

    st.markdown(f"#### {tr('recipe_options')}")
    for index, recipe in enumerate(recipes):
        selected = index == st.session_state.get("selected_recipe_index", 0)
        selected_class = " selected" if selected else ""
        st.html(
            f"""
            <div class="recipe-option{selected_class}">
                <p class="recipe-option-title">{index + 1}. {recipe.get("meal_title", "")}</p>
                <p class="recipe-option-copy">{recipe.get("reasoning_summary", "")}</p>
            </div>
            """
        )
        label = tr("current_recipe") if selected else tr("use_this_recipe")
        if st.button(label, key=f"select_recipe_{index}", use_container_width=True, disabled=selected):
            st.session_state["selected_recipe_index"] = index
            sync_cart(recipe)
            st.rerun()

    plan = normalize_plan(st.session_state.get("plan"))
    st.markdown(f"### {plan.get('meal_title', '')}")
    st.caption(st.session_state.get("status", ""))
    st.markdown(f"#### {tr('chef_note')}")
    st.caption(tr("chef_note_hint"))
    st.write(plan.get("chef_note") or plan.get("reasoning_summary", ""))

    col1, col2 = st.columns(2)
    col1.metric(tr("ingredients"), len(plan.get("owned_ingredients", [])))
    col2.metric(tr("missing"), len(plan.get("missing_items", [])))

    with st.expander(tr("uses"), expanded=True):
        st.write(", ".join(plan.get("owned_ingredients", [])))

    with st.expander(tr("missing"), expanded=True):
        missing = plan.get("missing_items", [])
        st.write(", ".join(missing) if missing else tr("all_set"))

    st.markdown(f"#### {tr('steps')}")
    for index, step in enumerate(plan.get("recipe_steps", []), start=1):
        st.write(f"{index}. {step}")


def render_cart():
    st.subheader(tr("cart"))
    plan = normalize_plan(st.session_state.get("plan"))
    if not plan:
        st.info(tr("no_cart"))
        return
    sync_cart(plan)
    products = plan.get("recommended_products", [])
    if not products:
        st.info(tr("all_set"))
        return

    for product in products:
        name = product.get("name", "")
        price = float(product.get("estimated_price", 0) or 0)
        st.markdown(f"**{name}**  {money(price)}")
        st.caption(product.get("reason", ""))
        c1, c2, c3 = st.columns([1, 1, 1])
        qty = int(st.session_state["cart_quantities"].get(name, 1))
        if c1.button("-", key=f"minus_{name}", use_container_width=True, disabled=qty <= 0):
            st.session_state["cart_quantities"][name] = max(0, qty - 1)
            st.rerun()
        c2.metric(tr("qty"), qty)
        if c3.button("+", key=f"plus_{name}", use_container_width=True):
            st.session_state["cart_quantities"][name] = qty + 1
            st.rerun()

    subtotal, count = cart_totals(plan)
    delivery = 1.99 if count else 0
    total = subtotal + delivery
    st.metric(tr("subtotal"), money(subtotal))
    st.metric(tr("delivery"), money(delivery))
    st.metric(tr("total"), money(total))

    col1, col2 = st.columns(2)
    if col1.button(tr("clear_cart"), use_container_width=True):
        for name in st.session_state["cart_quantities"]:
            st.session_state["cart_quantities"][name] = 0
        st.rerun()
    if col2.button(tr("reset_qty"), use_container_width=True):
        for name in st.session_state["cart_quantities"]:
            st.session_state["cart_quantities"][name] = 1
        st.rerun()
    if st.button(tr("place_order"), type="primary", use_container_width=True):
        st.success(tr("order_success"))


def render_settings(runtime_config):
    st.subheader(tr("settings"))
    language_label = st.radio(
        tr("language"),
        list(LANGUAGE_OPTIONS.keys()),
        index=list(LANGUAGE_OPTIONS.values()).index(lang()),
        horizontal=True,
    )
    selected_lang = LANGUAGE_OPTIONS[language_label]
    if selected_lang != lang():
        st.session_state["language"] = selected_lang
        st.session_state["manual_text"] = ""
        st.session_state["plan"] = None
        st.session_state["selected_recipe_index"] = 0
        st.session_state["business_goal"] = TEXT[selected_lang]["goal_options"][0]
        st.rerun()

    st.selectbox(tr("goal"), tr("goal_options"), key="business_goal")
    if runtime_config["ready"]:
        st.success(f"{tr('model_ready')}: {runtime_config['model']}")
    else:
        st.warning(runtime_config["error"])


def main():
    css()
    if "language" not in st.session_state:
        st.session_state["language"] = "en"
    if "ingredients" not in st.session_state:
        st.session_state["ingredients"] = []
    if "plan" not in st.session_state:
        st.session_state["plan"] = None
    if "cart_quantities" not in st.session_state:
        st.session_state["cart_quantities"] = {}
    if "manual_text" not in st.session_state:
        st.session_state["manual_text"] = ""
    if "business_goal" not in st.session_state:
        st.session_state["business_goal"] = tr("goal_options")[0]
    if "selected_recipe_index" not in st.session_state:
        st.session_state["selected_recipe_index"] = 0

    render_header()
    runtime_config = read_runtime_config()

    scan_tab, ingredients_tab, recipe_tab, cart_tab, settings_tab = st.tabs(
        [tr("scan"), tr("ingredients"), tr("recipe"), tr("cart"), tr("settings")]
    )

    with scan_tab:
        st.html('<div class="card">')
        render_scan(runtime_config)
        st.html("</div>")
    with ingredients_tab:
        st.html('<div class="card">')
        render_ingredients()
        st.html("</div>")
    with recipe_tab:
        st.html('<div class="card">')
        render_recipe(runtime_config, st.session_state.get("business_goal", tr("goal_options")[0]))
        st.html("</div>")
    with cart_tab:
        st.html('<div class="card">')
        render_cart()
        st.html("</div>")
    with settings_tab:
        st.html('<div class="card">')
        render_settings(runtime_config)
        st.html("</div>")


main()
