import base64
from datetime import datetime, timezone
import html
import json
import logging
import os
import re
import socket
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid

import streamlit as st

GEMINI_API_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"
GEMINI_API_ENABLE_URL = (
    "https://console.developers.google.com/apis/api/"
    "generativelanguage.googleapis.com/overview"
)
MODEL_SECRET_KEYS = ("model", "default_model")
API_KEY_ENV_KEYS = ("GOOGLE_API_KEY", "GEMINI_API_KEY", "API_KEY")
MODEL_ENV_KEYS = ("MODEL", "DEFAULT_MODEL", "GEMINI_MODEL")
BIGQUERY_PROJECT_ENV_KEYS = ("BIGQUERY_PROJECT_ID", "GOOGLE_CLOUD_PROJECT", "GCP_PROJECT")
BIGQUERY_DATASET_ENV_KEYS = ("BIGQUERY_DATASET", "FRESHWISE_BIGQUERY_DATASET")
BIGQUERY_TABLE_ENV_KEYS = ("BIGQUERY_EVENTS_TABLE", "FRESHWISE_BIGQUERY_EVENTS_TABLE")
RETAILER_ID_ENV_KEYS = ("RETAILER_ID", "FRESHWISE_RETAILER_ID")
PROMOTION_ID_ENV_KEYS = ("PROMOTION_ID", "FRESHWISE_PROMOTION_ID")
CURRENCY_ENV_KEYS = ("CURRENCY", "FRESHWISE_CURRENCY")
TENANT_CONFIG_VERSION_ENV_KEYS = ("TENANT_CONFIG_VERSION", "FRESHWISE_TENANT_CONFIG_VERSION")
DEFAULT_EVENTS_TABLE = "freshwise_events"
DEFAULT_RETAILER_ID = "demo-retailer"
DEFAULT_PROMOTION_ID = "demo-promotion"
DEFAULT_CURRENCY = "USD"
DEFAULT_TENANT_CONFIG_VERSION = "demo-v1"
GEMINI_TIMEOUT_SECONDS = 45
GEMINI_RETRY_TIMEOUT_SECONDS = 75

LANGUAGE_OPTIONS = {"English": "en", "中文": "zh"}

TEXT = {
    "en": {
        "app_title": "Freshwise",
        "tagline": "See it. Cook it. Love it.",
        "subtitle": "Identify fridge ingredients, generate a recipe, and order what is missing.",
        "journey_title": "Tonight's meal-to-cart path",
        "journey_subtitle": "Start with ingredients, choose dinner, then review the missing items.",
        "step_ingredients": "Ingredients",
        "step_recipes": "Pick dinner",
        "step_cart": "Missing items",
        "step_done": "Order",
        "step_ready": "Ready",
        "step_current": "Now",
        "step_waiting": "Next",
        "language": "Language",
        "settings": "Settings",
        "model_ready": "Model connected",
        "missing_secrets": "Missing Streamlit secrets: {items}",
        "goal": "Retail goal",
        "goal_options": [
            "Maximize basket value with relevant missing ingredients",
            "Prioritize fresh produce and dairy promotions",
            "Build a quick weeknight dinner plan",
            "Create a sponsored recipe placement",
        ],
        "scan": "Scan",
        "ingredients": "Ingredients",
        "recipe": "Recipe",
        "cart": "Cart",
        "admin": "Admin",
        "start_with_ingredients": "Start with what you have",
        "start_with_ingredients_hint": "Type the ingredients you can see. A fridge photo is useful too, but manual entry keeps the demo moving.",
        "photo_beta": "Photo scan",
        "manual_first": "Fast path",
        "camera": "Take a fridge photo",
        "recognize_photo": "Recognize Photo",
        "photo_hint": "On mobile, this opens the camera or photo picker.",
        "manual_input": "Manual ingredient input",
        "manual_placeholder": "tomatoes, spinach, eggs, cheese",
        "use_manual": "Use Manual Input",
        "use_demo": "Use Demo Ingredients",
        "detected": "Detected ingredients",
        "no_ingredients": "No ingredients yet. Take a photo or enter ingredients manually.",
        "no_recipe": "Add ingredients first, then generate three dinner options.",
        "no_cart": "Choose a recipe first, then review the missing items.",
        "empty_ingredients_title": "Tell Freshwise what is already in the kitchen.",
        "empty_recipe_title": "Your dinner options will appear here.",
        "empty_cart_title": "Missing items will turn into a mock cart.",
        "add_ingredient": "Add ingredient",
        "add": "Add",
        "remove": "Remove",
        "generate_recipe": "Generate Recipe",
        "regenerate": "Regenerate Recipe",
        "recipe_options": "Recipe options",
        "choose_recipe_hint": "Compare the options by effort, missing items, and basket impact.",
        "use_this_recipe": "Use this recipe",
        "current_recipe": "Current recipe",
        "model_generating": "Calling the configured multimodal model...",
        "model_recognizing": "Recognizing ingredients with the configured multimodal model...",
        "fallback_recipe": "Using local demo fallback because the model call was unavailable.",
        "fallback_photo": "Photo recognition needs a working multimodal model. Please confirm ingredients manually.",
        "generated_by_model": "Generated by the configured model.",
        "recognized_by_model": "Recognized by the configured model.",
        "meal": "Meal",
        "why": "Why this works",
        "chef_note": "Chef's inner monologue",
        "chef_note_hint": "A short, user-facing note about why this recipe direction makes sense.",
        "uses": "Uses",
        "missing": "Missing",
        "steps": "Steps",
        "recommended_products": "Recommended products",
        "missing_cart_title": "Items to complete this meal",
        "missing_cart_hint": "Adjust the recommended products before placing a mock order.",
        "product_reason": "Why it is here",
        "qty": "Qty",
        "subtotal": "Subtotal",
        "delivery": "Delivery",
        "total": "Total",
        "clear_cart": "Clear cart",
        "reset_qty": "Reset quantities",
        "place_order": "Place mock order",
        "order_success": "Mock order placed",
        "order_confirmation_title": "Mock order confirmed",
        "order_confirmation_body": "This demo order has been recorded for PoC analytics.",
        "order_number": "Order ID",
        "order_items": "Items",
        "order_total": "Order total",
        "need_ingredients": "Add at least one ingredient first.",
        "all_set": "All set",
        "photo_recognized_review": "Photo recognized. Please review the ingredients below.",
        "ingredients_updated": "Ingredients updated.",
        "recognized_results": "Recognized results",
        "local_demo": "Local demo",
        "admin_title": "PoC dashboard",
        "admin_poc_only": "Retailer-facing analytics. Keep this out of the shopper flow during demos.",
        "admin_disabled": "Analytics is not enabled for this environment.",
        "admin_empty": "No analytics events yet. Run through the meal-to-cart flow, then refresh this dashboard.",
        "admin_refresh": "Refresh dashboard",
        "admin_window": "Last 30 days",
        "admin_sessions": "Sessions",
        "admin_events": "Events",
        "admin_recipes": "Recipes generated",
        "admin_recommendations": "Product exposures",
        "admin_orders": "Mock orders",
        "admin_avg_cart": "Avg mock cart",
        "admin_top_ingredients": "Top ingredients",
        "admin_top_products": "Top recommended products",
        "admin_order_items": "Order line items",
        "admin_product_gmv": "Product mock GMV",
        "admin_promotion_performance": "Promotion performance",
        "admin_model_performance": "Model performance",
        "admin_recent_events": "Recent events",
    },
    "zh": {
        "app_title": "Freshwise",
        "tagline": "看見食材，做成料理，喜歡上晚餐。",
        "subtitle": "辨識冰箱食材、生成食譜，並把缺少的食材加入購物車。",
        "journey_title": "今晚的 meal-to-cart 流程",
        "journey_subtitle": "先確認食材，再選料理，最後檢查缺少商品。",
        "step_ingredients": "食材",
        "step_recipes": "選料理",
        "step_cart": "補缺料",
        "step_done": "訂單",
        "step_ready": "完成",
        "step_current": "目前",
        "step_waiting": "下一步",
        "language": "語言",
        "settings": "設定",
        "model_ready": "模型已連線",
        "missing_secrets": "缺少 Streamlit secrets：{items}",
        "goal": "零售目標",
        "goal_options": [
            "用相關缺少食材提高購物籃金額",
            "優先推動生鮮與乳製品促銷",
            "建立快速週間晚餐方案",
            "建立贊助食譜版位",
        ],
        "scan": "掃描",
        "ingredients": "食材",
        "recipe": "食譜",
        "cart": "購物車",
        "start_with_ingredients": "先輸入你已有的食材",
        "start_with_ingredients_hint": "直接輸入看得到的食材。照片辨識也可用，但手動輸入最適合穩定 demo。",
        "photo_beta": "照片辨識",
        "manual_first": "快速流程",
        "camera": "拍攝冰箱照片",
        "recognize_photo": "辨識照片",
        "photo_hint": "手機上會開啟相機或相簿。",
        "manual_input": "手動輸入食材",
        "manual_placeholder": "番茄、菠菜、雞蛋、起司",
        "use_manual": "使用手動輸入",
        "use_demo": "使用範例食材",
        "detected": "已辨識食材",
        "no_ingredients": "目前沒有食材。請拍照或手動輸入。",
        "no_recipe": "請先加入食材，再生成三個晚餐選項。",
        "no_cart": "請先選擇一道料理，再查看缺少商品。",
        "empty_ingredients_title": "告訴 Freshwise 廚房裡已經有什麼。",
        "empty_recipe_title": "晚餐選項會顯示在這裡。",
        "empty_cart_title": "缺少食材會變成模擬購物車。",
        "add_ingredient": "新增食材",
        "add": "新增",
        "remove": "移除",
        "generate_recipe": "生成食譜",
        "regenerate": "重新生成食譜",
        "recipe_options": "食譜選項",
        "choose_recipe_hint": "用缺少品項、購物金額與料理方向快速比較。",
        "use_this_recipe": "使用這道料理",
        "current_recipe": "目前料理",
        "model_generating": "正在呼叫設定的多模態模型...",
        "model_recognizing": "正在用設定的多模態模型辨識食材...",
        "fallback_recipe": "模型呼叫不可用，已改用本地 demo fallback。",
        "fallback_photo": "照片辨識需要可用的多模態模型，請手動確認食材。",
        "generated_by_model": "已由設定模型生成。",
        "recognized_by_model": "已由設定模型辨識。",
        "meal": "餐點",
        "why": "推薦原因",
        "chef_note": "大廚內心獨白",
        "chef_note_hint": "用給使用者看的方式，說明這道料理為什麼適合目前食材。",
        "uses": "使用食材",
        "missing": "缺少食材",
        "steps": "料理步驟",
        "recommended_products": "推薦商品",
        "missing_cart_title": "完成這道料理還缺這些",
        "missing_cart_hint": "送出模擬訂單前，可以先調整推薦商品數量。",
        "product_reason": "推薦原因",
        "qty": "數量",
        "subtotal": "小計",
        "delivery": "配送費",
        "total": "總計",
        "clear_cart": "清空購物車",
        "reset_qty": "重設數量",
        "place_order": "送出模擬訂單",
        "order_success": "模擬訂單已送出",
        "order_confirmation_title": "模擬訂單已確認",
        "order_confirmation_body": "這筆 demo 訂單已記錄到 PoC 分析事件。",
        "order_number": "訂單編號",
        "order_items": "品項數",
        "order_total": "訂單金額",
        "need_ingredients": "請至少加入一項食材。",
        "all_set": "完成",
        "photo_recognized_review": "照片已辨識，請確認下方食材。",
        "ingredients_updated": "食材已更新。",
        "recognized_results": "辨識結果",
        "local_demo": "本地範例",
        "admin": "管理",
        "admin_title": "PoC 儀表板",
        "admin_poc_only": "零售商分析頁。展示使用者流程時可先略過。",
        "admin_disabled": "此環境尚未啟用分析。",
        "admin_empty": "目前還沒有分析事件。請先跑一次 meal-to-cart 流程，再刷新儀表板。",
        "admin_refresh": "刷新儀表板",
        "admin_window": "最近 30 天",
        "admin_sessions": "工作階段",
        "admin_events": "事件",
        "admin_recipes": "已生成食譜",
        "admin_recommendations": "商品曝光",
        "admin_orders": "模擬訂單",
        "admin_avg_cart": "平均模擬購物車",
        "admin_top_ingredients": "熱門食材",
        "admin_top_products": "熱門推薦商品",
        "admin_order_items": "訂單品項",
        "admin_product_gmv": "商品模擬 GMV",
        "admin_promotion_performance": "活動成效",
        "admin_model_performance": "模型成效",
        "admin_recent_events": "最近事件",
    },
}

CATALOG = [
    {
        "catalog_product_id": "demo-heavy-cream",
        "name_en": "Heavy Cream",
        "name_zh": "鮮奶油",
        "category_en": "Dairy",
        "category_zh": "乳製品",
        "promotion_label_en": "Dinner sauce bundle",
        "promotion_label_zh": "晚餐醬汁組合",
        "price": 2.49,
        "reason_en": "Makes tomato sauce smooth and rich.",
        "reason_zh": "讓番茄醬汁更滑順濃郁。",
    },
    {
        "catalog_product_id": "demo-parmesan-cheese",
        "name_en": "Parmesan Cheese",
        "name_zh": "帕瑪森起司",
        "category_en": "Dairy",
        "category_zh": "乳製品",
        "promotion_label_en": "Italian night add-on",
        "promotion_label_zh": "義式晚餐加購",
        "price": 2.99,
        "reason_en": "Adds a nutty, salty finish.",
        "reason_zh": "增加鹹香與堅果風味。",
    },
    {
        "catalog_product_id": "demo-fresh-basil",
        "name_en": "Fresh Basil",
        "name_zh": "新鮮羅勒",
        "category_en": "Herbs",
        "category_zh": "香草",
        "promotion_label_en": "Fresh flavor boost",
        "promotion_label_zh": "清新風味加分",
        "price": 1.79,
        "reason_en": "Brings a fresh green lift.",
        "reason_zh": "讓料理更清新有層次。",
    },
    {
        "catalog_product_id": "demo-garlic",
        "name_en": "Garlic",
        "name_zh": "大蒜",
        "category_en": "Produce",
        "category_zh": "蔬果",
        "promotion_label_en": "Pantry essential",
        "promotion_label_zh": "料理基本配料",
        "price": 0.89,
        "reason_en": "Builds the savory base.",
        "reason_zh": "建立料理的鹹香底味。",
    },
    {
        "catalog_product_id": "demo-pasta",
        "name_en": "Pasta",
        "name_zh": "義大利麵",
        "category_en": "Pantry",
        "category_zh": "乾貨",
        "promotion_label_en": "Quick dinner base",
        "promotion_label_zh": "快速晚餐主食",
        "price": 1.99,
        "reason_en": "Turns fridge odds and ends into dinner.",
        "reason_zh": "把冰箱剩餘食材變成完整晚餐。",
    },
    {
        "catalog_product_id": "demo-cherry-tomatoes",
        "name_en": "Cherry Tomatoes",
        "name_zh": "小番茄",
        "category_en": "Produce",
        "category_zh": "蔬果",
        "promotion_label_en": "Fresh produce spotlight",
        "promotion_label_zh": "新鮮蔬果主打",
        "price": 3.49,
        "reason_en": "Cooks down into a sweet quick sauce.",
        "reason_zh": "能快速煮出清甜醬汁。",
    },
    {
        "catalog_product_id": "demo-baby-spinach",
        "name_en": "Baby Spinach",
        "name_zh": "嫩菠菜",
        "category_en": "Produce",
        "category_zh": "蔬果",
        "promotion_label_en": "Leafy greens feature",
        "promotion_label_zh": "葉菜促銷",
        "price": 2.79,
        "reason_en": "Adds fast-cooking greens to bowls, pasta, and eggs.",
        "reason_zh": "適合快速加入碗餐、義大利麵或蛋料理。",
    },
    {
        "catalog_product_id": "demo-free-range-eggs",
        "name_en": "Free Range Eggs",
        "name_zh": "放牧雞蛋",
        "category_en": "Protein",
        "category_zh": "蛋白質",
        "promotion_label_en": "Breakfast-to-dinner protein",
        "promotion_label_zh": "早晚餐蛋白質",
        "price": 4.49,
        "reason_en": "Turns leftovers into omelets, frittatas, and quick bowls.",
        "reason_zh": "能把剩餘食材做成歐姆蛋、烘蛋或快速碗餐。",
    },
    {
        "catalog_product_id": "demo-shredded-mozzarella",
        "name_en": "Shredded Mozzarella",
        "name_zh": "莫札瑞拉起司絲",
        "category_en": "Dairy",
        "category_zh": "乳製品",
        "promotion_label_en": "Melted cheese upgrade",
        "promotion_label_zh": "焗烤起司升級",
        "price": 3.29,
        "reason_en": "Melts cleanly into baked pasta, eggs, and toast.",
        "reason_zh": "適合焗烤義大利麵、蛋料理和吐司。",
    },
    {
        "catalog_product_id": "demo-chicken-breast",
        "name_en": "Chicken Breast",
        "name_zh": "雞胸肉",
        "category_en": "Protein",
        "category_zh": "蛋白質",
        "promotion_label_en": "Lean protein feature",
        "promotion_label_zh": "低脂蛋白主打",
        "price": 5.99,
        "reason_en": "Adds lean protein to salads, pasta, and rice bowls.",
        "reason_zh": "為沙拉、義大利麵和飯碗增加低脂蛋白質。",
    },
    {
        "catalog_product_id": "demo-jasmine-rice",
        "name_en": "Jasmine Rice",
        "name_zh": "茉莉香米",
        "category_en": "Pantry",
        "category_zh": "乾貨",
        "promotion_label_en": "Family meal staple",
        "promotion_label_zh": "家庭餐桌主食",
        "price": 6.49,
        "reason_en": "Creates a simple base for stir-fries and meal bowls.",
        "reason_zh": "可作為快炒和碗餐的簡單主食基底。",
    },
    {
        "catalog_product_id": "demo-extra-virgin-olive-oil",
        "name_en": "Extra Virgin Olive Oil",
        "name_zh": "特級初榨橄欖油",
        "category_en": "Pantry",
        "category_zh": "乾貨",
        "promotion_label_en": "Premium pantry upgrade",
        "promotion_label_zh": "高端乾貨升級",
        "price": 8.99,
        "reason_en": "Finishes vegetables, pasta, and simple sauces.",
        "reason_zh": "適合收尾蔬菜、義大利麵和簡單醬汁。",
    },
]

DEMO_INGREDIENTS = {
    "en": "tomatoes, spinach, eggs, cheese",
    "zh": "番茄、菠菜、雞蛋、起司",
}

FALLBACK_PLAN = {
    "en": {
        "meal_title": "Creamy Tomato Pasta",
        "reasoning_summary": "Use tomatoes and spinach as the fresh base, then add cream, parmesan, basil, and pasta to complete a fast dinner.",
        "chef_note": "I would lean into the tomatoes first, then use spinach for freshness and a creamy finish to make the dish feel complete.",
        "owned_ingredients": ["Tomatoes", "Spinach", "Cheese", "Eggs"],
        "missing_items": ["Heavy Cream", "Parmesan Cheese", "Fresh Basil"],
        "recommended_products": [
            {"name": "Heavy Cream", "reason": "Makes the sauce smooth.", "estimated_price": 2.49},
            {"name": "Parmesan Cheese", "reason": "Adds salty depth.", "estimated_price": 2.99},
            {"name": "Fresh Basil", "reason": "Finishes the dish fresh.", "estimated_price": 1.79},
        ],
        "recipe_steps": [
            "Boil pasta until al dente.",
            "Simmer tomatoes with garlic and a splash of cream.",
            "Fold in spinach, pasta, parmesan, and torn basil.",
        ],
        "cart_summary": {"item_count": 3, "estimated_total": 7.27},
    },
    "zh": {
        "meal_title": "奶油番茄義大利麵",
        "reasoning_summary": "用番茄與菠菜當新鮮基底，再補上鮮奶油、帕瑪森起司、羅勒與義大利麵，就能完成快速晚餐。",
        "chef_note": "我會先把番茄的酸甜煮出來，再用菠菜補清爽感，最後用奶油與起司把它收成一盤完整晚餐。",
        "owned_ingredients": ["番茄", "菠菜", "起司", "雞蛋"],
        "missing_items": ["鮮奶油", "帕瑪森起司", "新鮮羅勒"],
        "recommended_products": [
            {"name": "鮮奶油", "reason": "讓醬汁更滑順。", "estimated_price": 2.49},
            {"name": "帕瑪森起司", "reason": "增加鹹香深度。", "estimated_price": 2.99},
            {"name": "新鮮羅勒", "reason": "讓料理更清新。", "estimated_price": 1.79},
        ],
        "recipe_steps": [
            "將義大利麵煮到彈牙。",
            "用番茄、大蒜與少量鮮奶油煮成醬汁。",
            "拌入菠菜、義大利麵、起司與羅勒。",
        ],
        "cart_summary": {"item_count": 3, "estimated_total": 7.27},
    },
}

FALLBACK_RECIPE_VARIANTS = {
    "en": [
        {
            "meal_title": "Creamy Tomato Pasta",
            "reasoning_summary": "Use tomatoes and spinach as the fresh base, then add cream, parmesan, basil, and pasta to complete a fast dinner.",
            "chef_note": "I would lean into the tomatoes first, then use spinach for freshness and a creamy finish to make the dish feel complete.",
            "missing_items": ["Heavy Cream", "Parmesan Cheese", "Fresh Basil"],
            "recommended_products": [
                {"name": "Heavy Cream", "reason": "Makes the sauce smooth.", "estimated_price": 2.49},
                {"name": "Parmesan Cheese", "reason": "Adds salty depth.", "estimated_price": 2.99},
                {"name": "Fresh Basil", "reason": "Finishes the dish fresh.", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "Boil pasta until al dente.",
                "Simmer tomatoes with garlic and a splash of cream.",
                "Fold in spinach, pasta, parmesan, and torn basil.",
            ],
        },
        {
            "meal_title": "Spinach Cheese Omelet",
            "reasoning_summary": "Eggs and spinach become a fast protein-rich meal, with cheese for body and tomatoes for brightness.",
            "chef_note": "This is the quickest path when the fridge already has eggs: keep the center soft, then use tomatoes to wake it up.",
            "missing_items": ["Cherry Tomatoes", "Fresh Basil"],
            "recommended_products": [
                {"name": "Cherry Tomatoes", "reason": "Adds a juicy side.", "estimated_price": 3.49},
                {"name": "Fresh Basil", "reason": "Brightens the eggs.", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "Whisk eggs with a pinch of salt.",
                "Wilt spinach in a warm pan.",
                "Add eggs and cheese, fold gently, and serve with tomatoes and basil.",
            ],
        },
        {
            "meal_title": "Tomato Spinach Grain Bowl",
            "reasoning_summary": "Turn the ingredients into a flexible bowl by adding a grain base and a bright dressing.",
            "chef_note": "I would make this when you want something lighter than pasta but still complete enough to feel like dinner.",
            "missing_items": ["Pasta", "Fresh Basil"],
            "recommended_products": [
                {"name": "Pasta", "reason": "Works as the hearty base.", "estimated_price": 1.99},
                {"name": "Fresh Basil", "reason": "Adds a fresh finish.", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "Cook the grain or pasta base.",
                "Warm tomatoes until they soften and release juice.",
                "Toss with spinach, cheese, basil, and a drizzle of oil.",
            ],
        },
    ],
    "zh": [
        {
            "meal_title": "奶油番茄義大利麵",
            "reasoning_summary": "用番茄與菠菜當新鮮基底，再補上鮮奶油、帕瑪森起司、羅勒與義大利麵，就能完成快速晚餐。",
            "chef_note": "我會先把番茄的酸甜煮出來，再用菠菜補清爽感，最後用奶油與起司把它收成一盤完整晚餐。",
            "missing_items": ["鮮奶油", "帕瑪森起司", "新鮮羅勒"],
            "recommended_products": [
                {"name": "鮮奶油", "reason": "讓醬汁更滑順。", "estimated_price": 2.49},
                {"name": "帕瑪森起司", "reason": "增加鹹香層次。", "estimated_price": 2.99},
                {"name": "新鮮羅勒", "reason": "收尾更清爽。", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "將義大利麵煮到彈牙。",
                "把番茄與蒜炒軟，加入少量鮮奶油。",
                "拌入菠菜、義大利麵、起司與羅勒。",
            ],
        },
        {
            "meal_title": "菠菜起司歐姆蛋",
            "reasoning_summary": "雞蛋、菠菜與起司可以快速變成高蛋白餐點，再用番茄增加清爽酸甜。",
            "chef_note": "如果冰箱裡已經有蛋，我會走最快的路線：蛋保持柔嫩，番茄負責把味道點亮。",
            "missing_items": ["小番茄", "新鮮羅勒"],
            "recommended_products": [
                {"name": "小番茄", "reason": "做成多汁配菜。", "estimated_price": 3.49},
                {"name": "新鮮羅勒", "reason": "讓蛋香更清新。", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "雞蛋加鹽打散。",
                "菠菜下鍋炒軟。",
                "倒入蛋液與起司，摺成歐姆蛋，搭配番茄與羅勒。",
            ],
        },
        {
            "meal_title": "番茄菠菜溫沙拉碗",
            "reasoning_summary": "把現有食材做成清爽碗餐，補上一個主食基底與香草就能更完整。",
            "chef_note": "想吃得比義大利麵輕一點時，我會選這道；它簡單，但仍然像一份完整晚餐。",
            "missing_items": ["義大利麵", "新鮮羅勒"],
            "recommended_products": [
                {"name": "義大利麵", "reason": "作為飽足主食。", "estimated_price": 1.99},
                {"name": "新鮮羅勒", "reason": "增加清香。", "estimated_price": 1.79},
            ],
            "recipe_steps": [
                "煮好主食基底。",
                "番茄加熱到釋出汁水。",
                "拌入菠菜、起司、羅勒與少量橄欖油。",
            ],
        },
    ],
}

st.set_page_config(
    page_title="Freshwise",
    page_icon="FW",
    layout="centered",
    initial_sidebar_state="collapsed",
)


def lang():
    return st.session_state.get("language", "en")


def tr(key, **kwargs):
    value = TEXT.get(lang(), TEXT["en"]).get(key, TEXT["en"].get(key, key))
    return value.format(**kwargs) if kwargs else value


def money(value):
    return f"${float(value or 0):.2f}"


def get_secret_or_env(secret_keys, env_keys, default=""):
    try:
        value = next((st.secrets.get(key) for key in secret_keys if st.secrets.get(key)), None)
    except Exception:
        value = None
    return value or next((os.getenv(key) for key in env_keys if os.getenv(key)), default)


def normalize_ingredient_name(value, display=True):
    name = re.sub(r"\s+", " ", str(value or "").strip())
    if not name:
        return ""
    if re.search(r"[A-Za-z]", name):
        normalized = name.casefold()
        return normalized.title() if display else normalized
    return name


def normalize_ingredients(values, display=True):
    normalized = []
    seen = set()
    for value in values or []:
        name = normalize_ingredient_name(value, display=display)
        key = normalize_ingredient_name(value, display=False)
        if not name or key in seen:
            continue
        seen.add(key)
        normalized.append(name)
    return normalized


def ensure_session_id():
    if "analytics_session_id" not in st.session_state:
        st.session_state["analytics_session_id"] = uuid.uuid4().hex
    return st.session_state["analytics_session_id"]


def read_event_config():
    dataset = get_secret_or_env(("bigquery_dataset",), BIGQUERY_DATASET_ENV_KEYS)
    table = get_secret_or_env(("bigquery_events_table",), BIGQUERY_TABLE_ENV_KEYS, DEFAULT_EVENTS_TABLE)
    project_id = get_secret_or_env(("bigquery_project_id",), BIGQUERY_PROJECT_ENV_KEYS)
    return {"enabled": bool(dataset), "project_id": project_id, "dataset": dataset, "table": table}


def read_attribution_config():
    return {
        "retailer_id": get_secret_or_env(("retailer_id",), RETAILER_ID_ENV_KEYS, DEFAULT_RETAILER_ID),
        "promotion_id": get_secret_or_env(("promotion_id",), PROMOTION_ID_ENV_KEYS, DEFAULT_PROMOTION_ID),
        "model_name": st.session_state.get("model_name", ""),
        "currency": get_secret_or_env(("currency",), CURRENCY_ENV_KEYS, DEFAULT_CURRENCY),
        "tenant_config_version": get_secret_or_env(
            ("tenant_config_version",),
            TENANT_CONFIG_VERSION_ENV_KEYS,
            DEFAULT_TENANT_CONFIG_VERSION,
        ),
    }


@st.cache_resource(show_spinner=False)
def bigquery_event_table(project_id, dataset_id, table_id):
    from google.cloud import bigquery

    client = bigquery.Client(project=project_id or None)
    project = project_id or client.project
    dataset_ref = bigquery.Dataset(f"{project}.{dataset_id}")
    dataset_ref.location = "asia-east1"
    client.create_dataset(dataset_ref, exists_ok=True)

    full_table_id = f"{project}.{dataset_id}.{table_id}"
    schema = [
        bigquery.SchemaField("event_id", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("event_timestamp", "TIMESTAMP", mode="REQUIRED"),
        bigquery.SchemaField("event_name", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("session_id", "STRING"),
        bigquery.SchemaField("language", "STRING"),
        bigquery.SchemaField("business_goal", "STRING"),
        bigquery.SchemaField("ingredients", "STRING", mode="REPEATED"),
        bigquery.SchemaField("selected_recipe_index", "INTEGER"),
        bigquery.SchemaField("meal_title", "STRING"),
        bigquery.SchemaField("cart_item_count", "INTEGER"),
        bigquery.SchemaField("cart_subtotal", "FLOAT"),
        bigquery.SchemaField("properties_json", "STRING"),
    ]
    table = bigquery.Table(full_table_id, schema=schema)
    client.create_table(table, exists_ok=True)
    return client, full_table_id


def event_plan_snapshot(plan):
    if not plan:
        return {}
    subtotal, count = cart_totals(plan) if plan.get("recommended_products") else (0, 0)
    return {
        "meal_title": plan.get("meal_title", ""),
        "cart_item_count": count,
        "cart_subtotal": subtotal,
    }


def track_event(event_name, properties=None, plan=None):
    properties = {**read_attribution_config(), **(properties or {})}
    event_config = read_event_config()
    selected_plan = plan or normalize_plan(st.session_state.get("plan"))
    row = {
        "event_id": uuid.uuid4().hex,
        "event_timestamp": datetime.now(timezone.utc).isoformat(),
        "event_name": event_name,
        "session_id": ensure_session_id(),
        "language": lang(),
        "business_goal": st.session_state.get("business_goal", ""),
        "ingredients": normalize_ingredients(st.session_state.get("ingredients", [])),
        "selected_recipe_index": int(st.session_state.get("selected_recipe_index", 0)),
        "properties_json": json.dumps(properties, ensure_ascii=False, sort_keys=True),
        **event_plan_snapshot(selected_plan),
    }
    logging.info("freshwise_event %s", json.dumps(row, ensure_ascii=False, sort_keys=True))
    if not event_config["enabled"]:
        return
    try:
        client, table_id = bigquery_event_table(
            event_config["project_id"],
            event_config["dataset"],
            event_config["table"],
        )
        errors = client.insert_rows_json(table_id, [row])
        if errors:
            logging.error("BigQuery event insert failed: %s", errors)
    except Exception:
        logging.exception("BigQuery event logging failed")


def track_recommended_products(source):
    plan = normalize_plan(st.session_state.get("plan"))
    for index, product in enumerate(plan.get("recommended_products", [])):
        track_event(
            "product_recommended",
            {
                "source": source,
                "product_index": index,
                "catalog_product_id": product.get("catalog_product_id", ""),
                "product_name": product.get("name", ""),
                "category": product.get("category", ""),
                "promotion_label": product.get("promotion_label", ""),
                "estimated_price": float(product.get("estimated_price", 0) or 0),
            },
            plan,
        )


def product_event_properties(product, quantity, previous_quantity=None):
    quantity = int(quantity or 0)
    price = float(product.get("estimated_price", 0) or 0)
    properties = {
        "catalog_product_id": product.get("catalog_product_id", ""),
        "product_name": product.get("name", ""),
        "category": product.get("category", ""),
        "promotion_label": product.get("promotion_label", ""),
        "quantity": quantity,
        "estimated_price": price,
        "line_subtotal": round(price * quantity, 2),
        "reason": product.get("reason", ""),
    }
    if previous_quantity is not None:
        previous_quantity = int(previous_quantity or 0)
        properties["previous_quantity"] = previous_quantity
        properties["quantity_delta"] = quantity - previous_quantity
    return properties


def track_product_quantity_change(product, previous_quantity, quantity, plan):
    event_name = "product_added_to_cart" if quantity > previous_quantity else "product_removed_from_cart"
    track_event(event_name, product_event_properties(product, quantity, previous_quantity), plan)
    track_event(
        "cart_quantity_changed",
        product_event_properties(product, quantity, previous_quantity),
        plan,
    )


def track_order_line_items(plan, order_id):
    quantities = st.session_state.setdefault("cart_quantities", {})
    for product in plan.get("recommended_products", []):
        name = product.get("name", "")
        quantity = int(quantities.get(name, 0) or 0)
        if quantity <= 0:
            continue
        track_event(
            "order_line_item",
            {**product_event_properties(product, quantity), "order_id": order_id},
            plan,
        )


def row_to_dict(row):
    return {key: row[key] for key in row.keys()}


@st.cache_data(ttl=60, show_spinner=False)
def fetch_admin_dashboard(project_id, dataset_id, table_id):
    client, full_table_id = bigquery_event_table(project_id, dataset_id, table_id)
    table_ref = f"`{full_table_id}`"
    window_filter = "event_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)"

    metrics_sql = f"""
        SELECT
          COUNT(1) AS event_count,
          COUNT(DISTINCT session_id) AS session_count,
          COUNTIF(event_name = 'recipe_generated') AS recipe_count,
          COUNTIF(event_name = 'product_recommended') AS product_recommendation_count,
          COUNTIF(event_name = 'checkout_started') AS checkout_count,
          COUNTIF(event_name = 'order_completed') AS order_count,
          COUNTIF(event_name = 'order_line_item') AS order_line_item_count,
          AVG(IF(event_name = 'order_completed', cart_subtotal, NULL)) AS avg_order_cart_subtotal,
          SUM(
            IF(
              event_name = 'order_line_item',
              CAST(JSON_VALUE(properties_json, '$.line_subtotal') AS FLOAT64),
              0
            )
          ) AS product_mock_gmv
        FROM {table_ref}
        WHERE {window_filter}
    """
    top_ingredients_sql = f"""
        WITH normalized_ingredients AS (
          SELECT
            CASE
              WHEN REGEXP_CONTAINS(TRIM(ingredient), r'[A-Za-z]') THEN INITCAP(LOWER(TRIM(ingredient)))
              ELSE TRIM(ingredient)
            END AS normalized_ingredient
          FROM {table_ref}, UNNEST(ingredients) AS ingredient
          WHERE {window_filter}
            AND TRIM(ingredient) != ''
        )
        SELECT normalized_ingredient AS ingredient, COUNT(1) AS event_count
        FROM normalized_ingredients
        GROUP BY normalized_ingredient
        ORDER BY event_count DESC, ingredient
        LIMIT 10
    """
    top_products_sql = f"""
        SELECT
          JSON_VALUE(properties_json, '$.product_name') AS product_name,
          COUNT(1) AS exposure_count
        FROM {table_ref}
        WHERE {window_filter}
          AND event_name = 'product_recommended'
          AND JSON_VALUE(properties_json, '$.product_name') IS NOT NULL
        GROUP BY product_name
        ORDER BY exposure_count DESC, product_name
        LIMIT 10
    """
    ordered_products_sql = f"""
        SELECT
          JSON_VALUE(properties_json, '$.product_name') AS product_name,
          SUM(CAST(JSON_VALUE(properties_json, '$.quantity') AS INT64)) AS ordered_units,
          SUM(CAST(JSON_VALUE(properties_json, '$.line_subtotal') AS FLOAT64)) AS product_mock_gmv
        FROM {table_ref}
        WHERE {window_filter}
          AND event_name = 'order_line_item'
          AND JSON_VALUE(properties_json, '$.product_name') IS NOT NULL
        GROUP BY product_name
        ORDER BY product_mock_gmv DESC, ordered_units DESC, product_name
        LIMIT 10
    """
    promotion_performance_sql = f"""
        WITH session_events AS (
          SELECT
            session_id,
            JSON_VALUE(properties_json, '$.retailer_id') AS retailer_id,
            JSON_VALUE(properties_json, '$.promotion_id') AS promotion_id,
            MAX(IF(event_name = 'recipe_generated', 1, 0)) AS has_recipe,
            MAX(IF(event_name = 'checkout_started', 1, 0)) AS has_checkout,
            MAX(IF(event_name = 'order_completed', 1, 0)) AS has_order,
            MAX(IF(event_name = 'order_completed', cart_subtotal, NULL)) AS mock_order_value
          FROM {table_ref}
          WHERE {window_filter}
          GROUP BY session_id, retailer_id, promotion_id
        )
        SELECT
          retailer_id,
          promotion_id,
          COUNT(*) AS sessions,
          SUM(has_recipe) AS recipe_sessions,
          SUM(has_checkout) AS checkout_sessions,
          SUM(has_order) AS order_sessions,
          SAFE_DIVIDE(SUM(has_checkout), SUM(has_recipe)) AS recipe_to_checkout_rate,
          SUM(IFNULL(mock_order_value, 0)) AS mock_gmv
        FROM session_events
        GROUP BY retailer_id, promotion_id
        ORDER BY mock_gmv DESC, order_sessions DESC
        LIMIT 10
    """
    model_performance_sql = f"""
        SELECT
          JSON_VALUE(properties_json, '$.model_name') AS model_name,
          COUNTIF(event_name = 'recipe_generated') AS recipes_generated,
          COUNTIF(event_name = 'ingredient_detected') AS photo_recognitions,
          COUNTIF(event_name = 'order_completed') AS mock_orders,
          AVG(IF(event_name = 'order_completed', cart_subtotal, NULL)) AS average_mock_order_value
        FROM {table_ref}
        WHERE {window_filter}
        GROUP BY model_name
        ORDER BY recipes_generated DESC, mock_orders DESC
        LIMIT 10
    """
    recent_events_sql = f"""
        SELECT
          event_timestamp,
          event_name,
          session_id,
          meal_title,
          cart_item_count,
          cart_subtotal,
          properties_json
        FROM {table_ref}
        WHERE {window_filter}
        ORDER BY event_timestamp DESC
        LIMIT 25
    """

    metrics_rows = list(client.query(metrics_sql).result())
    metrics = row_to_dict(metrics_rows[0]) if metrics_rows else {}
    top_ingredients = [row_to_dict(row) for row in client.query(top_ingredients_sql).result()]
    top_products = [row_to_dict(row) for row in client.query(top_products_sql).result()]
    ordered_products = [row_to_dict(row) for row in client.query(ordered_products_sql).result()]
    promotion_performance = [row_to_dict(row) for row in client.query(promotion_performance_sql).result()]
    model_performance = [row_to_dict(row) for row in client.query(model_performance_sql).result()]
    recent_events = [row_to_dict(row) for row in client.query(recent_events_sql).result()]
    return {
        "metrics": metrics,
        "top_ingredients": top_ingredients,
        "top_products": top_products,
        "ordered_products": ordered_products,
        "promotion_performance": promotion_performance,
        "model_performance": model_performance,
        "recent_events": recent_events,
    }


THEME_COLORS = {
    "ink": "#123624",
    "ink_strong": "#0b2418",
    "muted": "#40573d",
    "subtle": "#586b51",
    "surface": "#fffdf7",
    "surface_strong": "#fbf8ee",
    "surface_soft": "#eef8e6",
    "primary": "#1f6f38",
    "primary_dark": "#164f2a",
    "control": "#e6f0dc",
    "disabled": "#f7f3e8",
    "success": "#dff2d8",
}


def hex_to_rgb(hex_color):
    value = hex_color.strip().lstrip("#")
    return tuple(int(value[index : index + 2], 16) for index in (0, 2, 4))


def relative_luminance(hex_color):
    channels = []
    for channel in hex_to_rgb(hex_color):
        normalized = channel / 255
        channels.append(normalized / 12.92 if normalized <= 0.04045 else ((normalized + 0.055) / 1.055) ** 2.4)
    return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2]


def contrast_ratio(color_a, color_b):
    lighter, darker = sorted((relative_luminance(color_a), relative_luminance(color_b)), reverse=True)
    return (lighter + 0.05) / (darker + 0.05)


def readable_text_for(background):
    light = THEME_COLORS["surface"]
    dark = THEME_COLORS["ink_strong"]
    return light if contrast_ratio(background, light) >= contrast_ratio(background, dark) else dark


def theme_css_variables():
    color_vars = [f"--fw-{key.replace('_', '-')}: {value};" for key, value in THEME_COLORS.items()]
    generated_vars = [
        f"--fw-on-primary: {readable_text_for(THEME_COLORS['primary'])};",
        f"--fw-on-primary-dark: {readable_text_for(THEME_COLORS['primary_dark'])};",
        f"--fw-on-control: {readable_text_for(THEME_COLORS['control'])};",
        f"--fw-on-disabled: {readable_text_for(THEME_COLORS['disabled'])};",
        f"--fw-on-success: {readable_text_for(THEME_COLORS['success'])};",
        "--fw-border: rgba(22, 63, 39, .18);",
    ]
    return "\n            ".join(color_vars + generated_vars)


def css():
    st.html(
        """
        <style>
        :root {
            {theme_vars}
        }
        .stApp {
            background:
                radial-gradient(circle at 16% 3%, rgba(186, 217, 125, .35), transparent 280px),
                linear-gradient(135deg, #fffdf7 0%, #f3efde 100%);
            color: var(--fw-ink);
        }
        .stApp,
        .stApp p,
        .stApp li,
        .stApp label,
        .stApp span,
        .stApp div[data-testid="stMarkdownContainer"],
        .stApp div[data-testid="stMarkdownContainer"] p,
        .stApp div[data-testid="stCaptionContainer"],
        .stApp div[data-testid="stMetric"] label,
        .stApp div[data-testid="stMetric"] [data-testid="stMetricValue"],
        .stApp div[data-testid="stMetric"] [data-testid="stMetricLabel"] {
            color: var(--fw-ink);
        }
        .stApp h1,
        .stApp h2,
        .stApp h3,
        .stApp h4,
        .stApp h5,
        .stApp h6 {
            color: var(--fw-ink-strong);
        }
        header[data-testid="stHeader"],
        .stAppHeader,
        [data-testid="stToolbar"],
        [data-testid="stDecoration"] {
            display: none !important;
            visibility: hidden !important;
            height: 0 !important;
            min-height: 0 !important;
            pointer-events: none !important;
        }
        .block-container {
            max-width: 840px;
            padding: 14px 14px 34px;
        }
        [role="radiogroup"] {
            display: inline-flex;
            gap: 6px;
            padding: 6px;
            margin-bottom: 10px;
            border: 1px solid var(--fw-border);
            border-radius: 999px;
            background: var(--fw-control);
            color: var(--fw-on-control);
        }
        [role="radiogroup"] label {
            min-height: 34px;
            padding: 6px 10px;
            border-radius: 999px;
            color: var(--fw-ink);
        }
        [role="radiogroup"] label:has(input:checked) {
            background: var(--fw-surface);
            box-shadow: 0 5px 12px rgba(34, 68, 38, .12);
        }
        .hero {
            padding: 20px 18px;
            border: 1px solid var(--fw-border);
            border-radius: 26px;
            background: rgba(255, 253, 247, .96);
            box-shadow: 0 18px 40px rgba(34, 68, 38, .10);
        }
        .brand {
            margin: 0 0 4px;
            color: var(--fw-primary-dark);
            font-size: 34px;
            font-weight: 900;
            letter-spacing: 0;
        }
        .tagline {
            margin: 0;
            color: var(--fw-muted);
            font-size: 15px;
            line-height: 1.5;
        }
        .journey {
            margin: 14px 0 2px;
            padding: 14px;
            border: 1px solid var(--fw-border);
            border-radius: 20px;
            background: rgba(255, 253, 247, .88);
        }
        .journey-title {
            margin: 0;
            color: var(--fw-ink-strong);
            font-size: 15px;
            font-weight: 900;
        }
        .journey-subtitle {
            margin: 4px 0 12px;
            color: var(--fw-muted);
            font-size: 13px;
            line-height: 1.45;
        }
        .journey-steps {
            display: grid;
            grid-template-columns: repeat(4, minmax(0, 1fr));
            gap: 8px;
        }
        .journey-step {
            min-height: 76px;
            padding: 10px;
            border: 1px solid var(--fw-border);
            border-radius: 16px;
            background: var(--fw-surface);
        }
        .journey-step.done {
            background: var(--fw-surface-soft);
        }
        .journey-step.active {
            border-color: var(--fw-primary);
            box-shadow: 0 10px 22px rgba(47, 123, 63, .14);
        }
        .journey-step-number {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 24px;
            height: 24px;
            border-radius: 999px;
            background: var(--fw-control);
            color: var(--fw-ink-strong);
            font-size: 12px;
            font-weight: 900;
        }
        .journey-step.active .journey-step-number {
            color: var(--fw-on-primary);
            background: var(--fw-primary);
        }
        .journey-step-label {
            margin: 8px 0 2px;
            color: var(--fw-ink-strong);
            font-size: 13px;
            font-weight: 900;
            line-height: 1.2;
        }
        .journey-step-status {
            margin: 0;
            color: var(--fw-muted);
            font-size: 12px;
            line-height: 1.25;
        }
        .section-kicker {
            margin: 0 0 4px;
            color: var(--fw-primary-dark);
            font-size: 12px;
            font-weight: 900;
            text-transform: uppercase;
            letter-spacing: .08em;
        }
        .empty-state {
            padding: 18px;
            border: 1px dashed rgba(31, 111, 56, .38);
            border-radius: 18px;
            background: rgba(238, 248, 230, .65);
        }
        .empty-title {
            margin: 0 0 4px;
            color: var(--fw-ink-strong);
            font-size: 16px;
            font-weight: 900;
        }
        .empty-copy {
            margin: 0;
            color: var(--fw-muted);
            font-size: 14px;
            line-height: 1.45;
        }
        .card {
            padding: 16px;
            border: 1px solid var(--fw-border);
            border-radius: 22px;
            background: rgba(255, 253, 247, .96);
            box-shadow: 0 10px 24px rgba(34, 68, 38, .08);
        }
        .recipe-option {
            margin: 10px 0;
            padding: 12px 14px;
            border: 1px solid var(--fw-border);
            border-radius: 18px;
            background: var(--fw-surface);
        }
        .recipe-option.selected {
            border: 2px solid var(--fw-primary);
            background: var(--fw-surface-soft);
            box-shadow: 0 12px 24px rgba(47, 123, 63, .16);
        }
        .recipe-option-title {
            margin: 0 0 4px;
            color: var(--fw-ink-strong);
            font-weight: 900;
        }
        .recipe-option-copy {
            margin: 0;
            color: var(--fw-muted);
            font-size: 14px;
            line-height: 1.45;
        }
        .recipe-option-meta {
            display: flex;
            flex-wrap: wrap;
            gap: 6px;
            margin-top: 10px;
        }
        .mini-pill {
            display: inline-flex;
            align-items: center;
            min-height: 28px;
            padding: 5px 9px;
            border-radius: 999px;
            background: var(--fw-control);
            color: var(--fw-ink-strong);
            font-size: 12px;
            font-weight: 800;
            line-height: 1.2;
        }
        .product-card {
            margin: 12px 0 6px;
            padding: 14px;
            border: 1px solid var(--fw-border);
            border-radius: 18px;
            background: var(--fw-surface);
        }
        .product-name {
            margin: 0;
            color: var(--fw-ink-strong);
            font-size: 16px;
            font-weight: 900;
        }
        .product-meta {
            margin: 5px 0 0;
            color: var(--fw-muted);
            font-size: 13px;
            line-height: 1.45;
        }
        .product-price {
            color: var(--fw-primary-dark);
            font-weight: 900;
        }
        .ingredient-strip {
            margin: 0 0 14px;
            padding: 12px;
            border: 1px solid var(--fw-border);
            border-radius: 18px;
            background: rgba(255, 253, 247, .78);
        }
        .ingredient-strip-title {
            margin: 0 0 8px;
            color: var(--fw-muted);
            font-size: 13px;
            font-weight: 800;
        }
        .ingredient-chip-row {
            display: flex;
            flex-wrap: wrap;
            gap: 7px;
        }
        .ingredient-chip {
            display: inline-flex;
            align-items: center;
            min-height: 30px;
            padding: 5px 10px;
            border: 1px solid rgba(31, 111, 56, .24);
            border-radius: 999px;
            background: #eaf5df;
            color: var(--fw-ink-strong);
            font-size: 13px;
            font-weight: 800;
            line-height: 1.2;
        }
        div[data-testid="stTabs"] {
            margin-top: 16px;
        }
        div[data-testid="stTabs"] div[role="tablist"] {
            display: grid;
            grid-template-columns: repeat(6, minmax(0, 1fr));
            gap: 6px;
            padding: 6px;
            border: 1px solid var(--fw-border);
            border-radius: 22px;
            background: var(--fw-control);
            box-shadow: inset 0 1px 0 rgba(255, 255, 255, .8);
        }
        div[data-testid="stTabs"] button[role="tab"] {
            min-height: 44px;
            padding: 8px 4px;
            border-radius: 16px;
            color: var(--fw-ink);
            font-weight: 800;
            border: 1px solid transparent;
            background: transparent;
        }
        div[data-testid="stTabs"] button[aria-selected="true"] {
            color: var(--fw-ink-strong);
            border-color: rgba(31, 111, 56, .35);
            background: var(--fw-surface);
            box-shadow: 0 8px 18px rgba(34, 68, 38, .10);
        }
        div[data-testid="stTabs"] [data-baseweb="tab-highlight"] {
            display: none;
        }
        @media (max-width: 430px) {
            .journey-steps {
                grid-template-columns: repeat(2, minmax(0, 1fr));
            }
            div[data-testid="stTabs"] div[role="tablist"] {
                grid-template-columns: repeat(3, minmax(0, 1fr));
            }
            div[data-testid="stTabs"] button[role="tab"] {
                font-size: 13px;
            }
        }
        .stButton > button {
            border-radius: 999px;
            min-height: 48px;
            font-weight: 800;
            color: var(--fw-ink-strong);
            border-color: rgba(31, 111, 56, .28);
            background: var(--fw-surface);
        }
        .stButton > button * {
            color: inherit;
        }
        .stButton > button[kind="primary"],
        .stButton > button[data-testid="baseButton-primary"] {
            color: var(--fw-on-primary) !important;
            border-color: var(--fw-primary-dark);
            background: var(--fw-primary) !important;
        }
        .stButton > button[kind="primary"] *,
        .stButton > button[data-testid="baseButton-primary"] * {
            color: var(--fw-on-primary) !important;
        }
        .stButton > button:disabled,
        button[data-testid="stCameraInputButton"]:disabled,
        button[data-testid="baseButton-primary"]:disabled,
        button[data-testid="baseButton-secondary"]:disabled {
            color: var(--fw-on-disabled) !important;
            border-color: rgba(22, 63, 39, .22);
            background: var(--fw-disabled) !important;
            opacity: 1;
        }
        .stButton > button:disabled *,
        button[data-testid="stCameraInputButton"]:disabled *,
        button[data-testid="baseButton-primary"]:disabled *,
        button[data-testid="baseButton-secondary"]:disabled * {
            color: var(--fw-on-disabled) !important;
        }
        .stTextArea textarea,
        .stTextInput input,
        div[data-baseweb="select"] > div {
            color: var(--fw-ink-strong);
            border-color: var(--fw-border);
            background: var(--fw-surface);
        }
        .stTextArea textarea::placeholder,
        .stTextInput input::placeholder {
            color: var(--fw-subtle);
            opacity: 1;
        }
        [data-testid="stMetric"] {
            border: 1px solid var(--fw-border);
            border-radius: 18px;
            padding: 10px;
            background: rgba(255, 253, 247, .96);
        }
        [data-testid="stExpander"] {
            border-color: var(--fw-border);
            background: rgba(255, 253, 247, .9);
        }
        .stAlert {
            color: var(--fw-on-success);
        }
        .stAlert * {
            color: inherit;
        }
        a {
            color: var(--fw-primary-dark);
        }
        </style>
        """
        .replace("{theme_vars}", theme_css_variables())
    )


def read_runtime_config():
    api_key = get_secret_or_env(("api_key",), API_KEY_ENV_KEYS)
    configured_model = get_secret_or_env(MODEL_SECRET_KEYS, MODEL_ENV_KEYS)
    model = normalize_gemini_model_name(configured_model)
    if model:
        st.session_state["model_name"] = model

    missing = []
    if not api_key:
        missing.append("api_key/GOOGLE_API_KEY")
    if not configured_model:
        missing.append("default_model/model/DEFAULT_MODEL")
    if missing:
        return {"ready": False, "api_key": "", "model": "", "error": tr("missing_secrets", items=", ".join(missing))}
    return {"ready": True, "api_key": api_key, "model": model, "error": ""}


def normalize_gemini_model_name(model):
    value = (model or "").strip()
    if not value:
        return ""
    value = value.split("?", 1)[0].split(":generateContent", 1)[0].strip("/")
    if value.startswith(GEMINI_API_BASE_URL):
        value = value.removeprefix(GEMINI_API_BASE_URL).strip("/")
    if value.startswith("models/"):
        value = value.removeprefix("models/")
    return value


def parse_ingredients(text):
    parts = re.split(r"[,，、\n]+", text or "")
    return normalize_ingredients(parts)


def catalog_prompt():
    suffix = lang()
    rows = []
    for item in CATALOG:
        rows.append(
            f"- {item['catalog_product_id']} / {item[f'name_{suffix}']} / {item[f'category_{suffix}']} / "
            f"{item[f'promotion_label_{suffix}']} / ${item['price']:.2f} / {item[f'reason_{suffix}']}"
        )
    return "\n".join(rows)


def catalog_item_for_product_name(name):
    product_name = normalize_ingredient_name(name, display=False)
    for item in CATALOG:
        names = (
            normalize_ingredient_name(item.get("name_en", ""), display=False),
            normalize_ingredient_name(item.get("name_zh", ""), display=False),
        )
        if product_name in names:
            return item
    return None


def enrich_recommended_product(product):
    product = dict(product or {})
    catalog_item = catalog_item_for_product_name(product.get("name", ""))
    if catalog_item:
        product.setdefault("catalog_product_id", catalog_item["catalog_product_id"])
        product.setdefault("estimated_price", catalog_item["price"])
        product.setdefault("category", catalog_item[f"category_{lang()}"])
        product.setdefault("promotion_label", catalog_item[f"promotion_label_{lang()}"])
    return product


def clean_response(raw):
    raw = re.sub(r"<thought>.*?</thought>", "", raw or "", flags=re.DOTALL | re.IGNORECASE)
    raw = re.sub(r"```[a-zA-Z]*\n?|```", "", raw)
    return raw.strip()


def extract_json(raw):
    cleaned = clean_response(raw)
    match = re.search(r"(\{.*\})", cleaned, re.DOTALL)
    if not match:
        raise ValueError("No JSON object found.")
    return json.loads(match.group(1))


def call_gemini(api_key, model, user_parts, system_prompt):
    model_path = urllib.parse.quote(normalize_gemini_model_name(model), safe="")
    url = f"{GEMINI_API_BASE_URL}/models/{model_path}:generateContent?key={urllib.parse.quote(api_key)}"
    payload = {
        "systemInstruction": {"parts": [{"text": system_prompt}]},
        "contents": [{"role": "user", "parts": user_parts}],
        "generationConfig": {"responseMimeType": "application/json"},
    }
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    data = None
    timeouts = (GEMINI_TIMEOUT_SECONDS, GEMINI_RETRY_TIMEOUT_SECONDS)
    for attempt, timeout_seconds in enumerate(timeouts, start=1):
        try:
            with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
                data = json.loads(response.read().decode("utf-8"))
            break
        except (TimeoutError, socket.timeout) as exc:
            if attempt == len(timeouts):
                raise RuntimeError(
                    f"Gemini request timed out after {timeout_seconds} seconds. "
                    "Freshwise switched to the local demo plan so the meal-to-cart flow can continue."
                ) from exc
            logging.warning("Gemini request timed out after %s seconds; retrying once.", timeout_seconds)
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"Gemini HTTP {exc.code}: {detail}") from exc
        except urllib.error.URLError as exc:
            reason = exc.reason
            if isinstance(reason, TimeoutError) or isinstance(reason, socket.timeout):
                if attempt == len(timeouts):
                    raise RuntimeError(
                        f"Gemini request timed out after {timeout_seconds} seconds. "
                        "Freshwise switched to the local demo plan so the meal-to-cart flow can continue."
                    ) from exc
                logging.warning("Gemini connection timed out after %s seconds; retrying once.", timeout_seconds)
                continue
            raise RuntimeError(f"Gemini connection failed: {reason}") from exc

    parts = data.get("candidates", [{}])[0].get("content", {}).get("parts", [])
    text = "".join(part.get("text", "") for part in parts if isinstance(part, dict)).strip()
    if not text:
        raise ValueError(f"Gemini response missing text: {json.dumps(data)[:500]}")
    return text


def generate_plan(api_key, model, ingredients, business_goal):
    output_language = "Traditional Chinese" if lang() == "zh" else "English"
    system_prompt = f"""
You are Freshwise, a multimodal meal-to-cart engine for a grocery app.
Create exactly three practical dinner recommendations from the user's ingredients and the retailer promotion catalog.
Recommend missing items only when useful for the recipe.
Output language: {output_language}.
Business goal: {business_goal}

Promotion catalog:
{catalog_prompt()}

Return only valid JSON with this shape:
{{
  "recipes": [
    {{
      "meal_title": "string",
      "reasoning_summary": "string",
      "chef_note": "string",
      "owned_ingredients": ["string"],
      "missing_items": ["string"],
      "recommended_products": [
        {{"catalog_product_id": "string", "name": "string", "category": "string", "promotion_label": "string", "reason": "string", "estimated_price": 0}}
      ],
      "recipe_steps": ["string"],
      "cart_summary": {{"item_count": 0, "estimated_total": 0}}
    }}
  ]
}}
"""
    raw = call_gemini(
        api_key,
        model,
        [{"text": f"Ingredients: {', '.join(ingredients)}"}],
        system_prompt,
    )
    data = extract_json(raw)
    if isinstance(data.get("recipes"), list):
        data["recipes"] = data["recipes"][:3]
    elif not isinstance(data.get("recommended_products"), list):
        raise ValueError("Model JSON missing recipes.")
    return data


def recognize_ingredients(api_key, model, image_bytes):
    output_language = "Traditional Chinese" if lang() == "zh" else "English"
    encoded = base64.b64encode(image_bytes).decode("ascii")
    raw = call_gemini(
        api_key,
        model,
        [
            {"text": "Identify the visible food ingredients."},
            {"inlineData": {"mimeType": "image/jpeg", "data": encoded}},
        ],
        (
            "You identify visible food ingredients from fridge or kitchen photos. "
            f"Return only JSON in {output_language}: "
            '{"ingredients":["ingredient name"]}. Do not include non-food objects.'
        ),
    )
    data = extract_json(raw)
    ingredients = data.get("ingredients", [])
    if not isinstance(ingredients, list):
        raise ValueError("Model JSON missing ingredients.")
    return normalize_ingredients(ingredients)


def fallback_plan(ingredients):
    owned = ingredients or FALLBACK_PLAN[lang()]["owned_ingredients"]
    recipes = []
    for variant in FALLBACK_RECIPE_VARIANTS[lang()]:
        recipe = {**FALLBACK_PLAN[lang()], **variant}
        recipe["owned_ingredients"] = owned
        recipes.append(recipe)
    return {"recipes": recipes}


def recipe_options(plan):
    if not plan:
        return []
    raw = plan
    recipes = raw.get("recipes") if isinstance(raw, dict) else None
    if not isinstance(recipes, list) or not recipes:
        recipes = [raw]
    normalized = []
    base = FALLBACK_PLAN[lang()]
    for recipe in recipes[:3]:
        merged = {**base, **(recipe or {})}
        merged["owned_ingredients"] = merged.get("owned_ingredients") or base["owned_ingredients"]
        merged["missing_items"] = merged.get("missing_items") or base["missing_items"]
        merged["recommended_products"] = merged.get("recommended_products") or base["recommended_products"]
        merged["recommended_products"] = [
            enrich_recommended_product(product) for product in merged["recommended_products"]
        ]
        merged["recipe_steps"] = merged.get("recipe_steps") or base["recipe_steps"]
        merged["chef_note"] = merged.get("chef_note") or merged.get("reasoning_summary") or base.get("chef_note", "")
        normalized.append(merged)
    return normalized


def normalize_plan(plan):
    recipes = recipe_options(plan)
    if not recipes:
        return {}
    selected = min(st.session_state.get("selected_recipe_index", 0), len(recipes) - 1)
    st.session_state["selected_recipe_index"] = selected
    return recipes[selected]


def sync_cart(plan):
    cart = st.session_state.setdefault("cart_quantities", {})
    product_names = [product.get("name", "") for product in plan["recommended_products"]]
    for name in product_names:
        cart.setdefault(name, 1)
    for name in list(cart):
        if name not in product_names:
            del cart[name]


def cart_totals(plan):
    subtotal = 0.0
    count = 0
    quantities = st.session_state.setdefault("cart_quantities", {})
    for product in plan["recommended_products"]:
        name = product.get("name", "")
        qty = int(quantities.get(name, 1))
        subtotal += float(product.get("estimated_price", 0) or 0) * qty
        count += qty
    return round(subtotal, 2), count


def cart_line_items(plan):
    quantities = st.session_state.setdefault("cart_quantities", {})
    items = []
    for product in plan.get("recommended_products", []):
        name = product.get("name", "")
        qty = int(quantities.get(name, 0) or 0)
        if qty <= 0:
            continue
        price = float(product.get("estimated_price", 0) or 0)
        items.append(
            {
                tr("recommended_products"): name,
                tr("qty"): qty,
                tr("subtotal"): money(price * qty),
            }
        )
    return items


def render_order_confirmation():
    order = st.session_state.get("last_mock_order")
    if not order:
        return
    with st.container(border=True):
        st.success(tr("order_success"))
        st.markdown(f"### {tr('order_confirmation_title')}")
        st.caption(tr("order_confirmation_body"))
        cols = st.columns(3)
        cols[0].metric(tr("order_items"), int(order.get("item_count", 0)))
        cols[1].metric(tr("order_total"), money(order.get("total", 0)))
        cols[2].metric(tr("order_number"), str(order.get("order_id", ""))[:8].upper())
        if order.get("items"):
            st.dataframe(order["items"], hide_index=True, use_container_width=True)


def clear_order_state():
    st.session_state.pop("last_mock_order", None)


def set_demo():
    ingredients = parse_ingredients(DEMO_INGREDIENTS[lang()])
    clear_order_state()
    st.session_state["ingredients"] = ingredients
    st.session_state["manual_text"] = DEMO_INGREDIENTS[lang()]
    st.session_state["plan"] = fallback_plan(ingredients)
    st.session_state["selected_recipe_index"] = 0
    st.session_state["status"] = tr("local_demo")
    track_event("demo_ingredients_loaded", {"ingredient_count": len(ingredients)})


def ingredients_to_text(ingredients):
    separator = ", " if lang() == "en" else "、"
    return separator.join(ingredients)


def render_selected_ingredients():
    ingredients = st.session_state.get("ingredients", [])
    if not ingredients:
        st.info(tr("no_ingredients"))
        return
    chips = "".join(
        f'<span class="ingredient-chip">{html.escape(str(ingredient))}</span>'
        for ingredient in ingredients
    )
    st.html(
        f"""
        <div class="ingredient-strip">
            <p class="ingredient-strip-title">{html.escape(tr("ingredients"))}</p>
            <div class="ingredient-chip-row">{chips}</div>
        </div>
        """
    )


def format_model_error(exc):
    detail = str(exc)
    if "timed out" in detail or "read operation timed out" in detail:
        return (
            "Gemini took too long to respond. Freshwise kept the demo moving with a local recipe plan; "
            "try regenerating in a moment."
        )
    if "unexpected model name format" in detail or "GenerateContentRequest.model" in detail:
        return (
            "Gemini model name format is invalid. Use a model id such as "
            "gemini-2.5-flash or models/gemini-2.5-flash; Freshwise will normalize it before calling Gemini."
        )
    if "SERVICE_DISABLED" in detail or "Gemini API has not been used" in detail:
        return (
            "Gemini API is disabled for this Google Cloud project. Enable it here: "
            f"{GEMINI_API_ENABLE_URL}. If you just enabled it, wait a few minutes and retry."
        )
    if "API_KEY_SERVICE_BLOCKED" in detail or "Requests to this API" in detail:
        return (
            "This API key is blocking Gemini requests. In Google Cloud Console, open the "
            "API key restrictions and allow Generative Language API "
            "(generativelanguage.googleapis.com), or temporarily set API restrictions to "
            "unrestricted while testing."
        )
    if "PERMISSION_DENIED" in detail or "Error code: 403" in detail:
        return (
            "Gemini returned 403 PERMISSION_DENIED. Check that the API key belongs to a "
            "project with Gemini API enabled and that the key is allowed to call it."
        )
    return detail


def generate_recipe(runtime_config, business_goal):
    ingredients = st.session_state.get("ingredients", [])
    if not ingredients:
        st.warning(tr("need_ingredients"))
        return
    clear_order_state()
    started_at = time.perf_counter()
    if runtime_config["ready"]:
        try:
            with st.spinner(tr("model_generating")):
                st.session_state["plan"] = generate_plan(
                    runtime_config["api_key"],
                    runtime_config["model"],
                    ingredients,
                    business_goal,
                )
                st.session_state["selected_recipe_index"] = 0
            st.session_state["status"] = tr("generated_by_model")
            track_event(
                "recipe_generated",
                {
                    "source": "model",
                    "recipe_count": len(recipe_options(st.session_state.get("plan"))),
                    "recipe_generation_latency_ms": int((time.perf_counter() - started_at) * 1000),
                    "estimated_request_count": 1,
                },
            )
            track_recommended_products("model")
            return
        except Exception as exc:
            logging.exception("Recipe generation failed")
            st.warning(f"{tr('fallback_recipe')} ({format_model_error(exc)})")
    else:
        st.warning(runtime_config["error"])
    st.session_state["plan"] = fallback_plan(ingredients)
    st.session_state["selected_recipe_index"] = 0
    st.session_state["status"] = tr("fallback_recipe")
    track_event(
        "recipe_generated",
        {
            "source": "fallback",
            "recipe_count": len(recipe_options(st.session_state.get("plan"))),
            "recipe_generation_latency_ms": int((time.perf_counter() - started_at) * 1000),
            "estimated_request_count": 1 if runtime_config["ready"] else 0,
        },
    )
    track_recommended_products("fallback")


def render_header():
    st.html(
        f"""
        <div class="hero">
            <h1 class="brand">{tr("app_title")}</h1>
            <p class="tagline"><strong>{tr("tagline")}</strong><br>{tr("subtitle")}</p>
        </div>
        """
    )


def render_empty_state(title, copy):
    st.html(
        f"""
        <div class="empty-state">
            <p class="empty-title">{html.escape(title)}</p>
            <p class="empty-copy">{html.escape(copy)}</p>
        </div>
        """
    )


def render_journey():
    has_ingredients = bool(st.session_state.get("ingredients"))
    recipes = recipe_options(st.session_state.get("plan"))
    has_recipe = bool(recipes)
    has_order = bool(st.session_state.get("last_mock_order"))
    if has_order:
        active_index = 3
    elif has_recipe:
        active_index = 2
    elif has_ingredients:
        active_index = 1
    else:
        active_index = 0

    steps = [
        (tr("step_ingredients"), has_ingredients),
        (tr("step_recipes"), has_recipe),
        (tr("step_cart"), has_recipe),
        (tr("step_done"), has_order),
    ]
    step_html = []
    for index, (label, done) in enumerate(steps):
        state = "active" if index == active_index else "done" if done else ""
        status = tr("step_current") if index == active_index else tr("step_ready") if done else tr("step_waiting")
        step_html.append(
            f"""
            <div class="journey-step {state}">
                <span class="journey-step-number">{index + 1}</span>
                <p class="journey-step-label">{html.escape(label)}</p>
                <p class="journey-step-status">{html.escape(status)}</p>
            </div>
            """
        )
    st.html(
        f"""
        <div class="journey">
            <p class="journey-title">{html.escape(tr("journey_title"))}</p>
            <p class="journey-subtitle">{html.escape(tr("journey_subtitle"))}</p>
            <div class="journey-steps">{''.join(step_html)}</div>
        </div>
        """
    )


def render_scan(runtime_config):
    st.markdown(f'<p class="section-kicker">{html.escape(tr("manual_first"))}</p>', unsafe_allow_html=True)
    st.subheader(tr("start_with_ingredients"))
    st.caption(tr("start_with_ingredients_hint"))
    manual = st.text_area(
        tr("manual_input"),
        placeholder=tr("manual_placeholder"),
        key="manual_text",
    )
    col1, col2 = st.columns(2)
    if col1.button(tr("use_manual"), use_container_width=True):
        ingredients = parse_ingredients(manual)
        if ingredients:
            clear_order_state()
            st.session_state["ingredients"] = ingredients
            st.session_state["plan"] = None
            st.session_state["selected_recipe_index"] = 0
            track_event("ingredients_updated", {"source": "manual", "ingredient_count": len(ingredients)})
            st.success(tr("ingredients_updated"))
        else:
            st.warning(tr("need_ingredients"))
    col2.button(tr("use_demo"), use_container_width=True, on_click=set_demo)

    st.markdown("---")
    st.markdown(f'<p class="section-kicker">{html.escape(tr("photo_beta"))}</p>', unsafe_allow_html=True)
    photo = st.camera_input(tr("camera"), help=tr("photo_hint"))
    if st.button(tr("recognize_photo"), use_container_width=True, disabled=photo is None):
        if not runtime_config["ready"]:
            st.warning(tr("fallback_photo"))
        else:
            try:
                started_at = time.perf_counter()
                with st.spinner(tr("model_recognizing")):
                    ingredients = recognize_ingredients(runtime_config["api_key"], runtime_config["model"], photo.getvalue())
                clear_order_state()
                st.session_state["ingredients"] = ingredients
                st.session_state["manual_text"] = ingredients_to_text(ingredients)
                st.session_state["plan"] = None
                st.session_state["selected_recipe_index"] = 0
                st.session_state["status"] = tr("recognized_by_model")
                track_event(
                    "ingredient_detected",
                    {
                        "source": "photo",
                        "ingredient_count": len(ingredients),
                        "photo_recognition_latency_ms": int((time.perf_counter() - started_at) * 1000),
                        "estimated_request_count": 1,
                    },
                )
                st.success(tr("photo_recognized_review"))
            except Exception as exc:
                logging.exception("Photo recognition failed")
                st.warning(f"{tr('fallback_photo')} ({format_model_error(exc)})")


def render_ingredients():
    st.subheader(tr("detected"))
    ingredients = st.session_state.get("ingredients", [])
    if not ingredients:
        render_empty_state(tr("empty_ingredients_title"), tr("no_ingredients"))
    for index, ingredient in enumerate(list(ingredients)):
        col1, col2 = st.columns([3, 1])
        col1.write(f"**{ingredient}**")
        if col2.button(tr("remove"), key=f"remove_{index}", use_container_width=True):
            clear_order_state()
            ingredients.pop(index)
            st.session_state["ingredients"] = ingredients
            st.session_state["plan"] = None
            st.session_state["selected_recipe_index"] = 0
            track_event("ingredient_removed", {"ingredient": ingredient, "ingredient_count": len(ingredients)})
            st.rerun()

    new_item = st.text_input(tr("add_ingredient"), key="new_ingredient")
    if st.button(tr("add"), use_container_width=True):
        value = normalize_ingredient_name(new_item)
        if value:
            clear_order_state()
            st.session_state["ingredients"] = normalize_ingredients([*ingredients, value])
            st.session_state["plan"] = None
            st.session_state["selected_recipe_index"] = 0
            track_event(
                "ingredient_added",
                {"ingredient": value, "ingredient_count": len(st.session_state["ingredients"])},
            )
            st.rerun()


def recipe_option_html(index, recipe, selected):
    selected_class = " selected" if selected else ""
    products = recipe.get("recommended_products", [])
    count = len(products)
    subtotal = sum(float(product.get("estimated_price", 0) or 0) for product in products)
    meta = [
        f'{tr("uses")}: {len(recipe.get("owned_ingredients", []))}',
        f'{tr("missing")}: {len(recipe.get("missing_items", []))}',
        f'{tr("recommended_products")}: {count}',
        money(subtotal),
    ]
    pills = "".join(f'<span class="mini-pill">{html.escape(str(item))}</span>' for item in meta)
    return f"""
        <div class="recipe-option{selected_class}">
            <p class="recipe-option-title">{index + 1}. {html.escape(str(recipe.get("meal_title", "")))}</p>
            <p class="recipe-option-copy">{html.escape(str(recipe.get("reasoning_summary", "")))}</p>
            <div class="recipe-option-meta">{pills}</div>
        </div>
        """


def render_recipe(runtime_config, business_goal):
    st.subheader(tr("recipe"))
    render_selected_ingredients()
    button_label = tr("regenerate") if recipe_options(st.session_state.get("plan")) else tr("generate_recipe")
    if st.button(button_label, type="primary", use_container_width=True):
        generate_recipe(runtime_config, business_goal)

    recipes = recipe_options(st.session_state.get("plan"))
    if not recipes:
        render_empty_state(tr("empty_recipe_title"), tr("no_recipe"))
        return

    st.markdown(f"#### {tr('recipe_options')}")
    st.caption(tr("choose_recipe_hint"))
    for index, recipe in enumerate(recipes):
        selected = index == st.session_state.get("selected_recipe_index", 0)
        st.html(recipe_option_html(index, recipe, selected))
        label = tr("current_recipe") if selected else tr("use_this_recipe")
        if st.button(label, key=f"select_recipe_{index}", use_container_width=True, disabled=selected):
            clear_order_state()
            st.session_state["selected_recipe_index"] = index
            sync_cart(recipe)
            track_event("recipe_selected", {"recipe_index": index}, recipe)
            st.rerun()

    plan = normalize_plan(st.session_state.get("plan"))
    st.markdown(f"### {plan.get('meal_title', '')}")
    st.caption(st.session_state.get("status", ""))
    st.markdown(f"#### {tr('chef_note')}")
    st.caption(tr("chef_note_hint"))
    st.write(plan.get("chef_note") or plan.get("reasoning_summary", ""))

    col1, col2 = st.columns(2)
    col1.metric(tr("ingredients"), len(plan.get("owned_ingredients", [])))
    col2.metric(tr("missing"), len(plan.get("missing_items", [])))

    with st.expander(tr("uses"), expanded=True):
        st.write(", ".join(plan.get("owned_ingredients", [])))

    with st.expander(tr("missing"), expanded=True):
        missing = plan.get("missing_items", [])
        st.write(", ".join(missing) if missing else tr("all_set"))

    st.markdown(f"#### {tr('steps')}")
    for index, step in enumerate(plan.get("recipe_steps", []), start=1):
        st.write(f"{index}. {step}")


def render_cart():
    st.subheader(tr("cart"))
    plan = normalize_plan(st.session_state.get("plan"))
    if not plan:
        render_empty_state(tr("empty_cart_title"), tr("no_cart"))
        return
    render_order_confirmation()
    sync_cart(plan)
    products = plan.get("recommended_products", [])
    if not products:
        st.info(tr("all_set"))
        return

    st.markdown(f"#### {tr('missing_cart_title')}")
    st.caption(tr("missing_cart_hint"))
    for product in products:
        name = product.get("name", "")
        price = float(product.get("estimated_price", 0) or 0)
        category = product.get("category", "")
        promotion = product.get("promotion_label", "")
        reason = product.get("reason", "")
        details = " · ".join(value for value in [category, promotion] if value)
        st.html(
            f"""
            <div class="product-card">
                <p class="product-name">{html.escape(str(name))} <span class="product-price">{money(price)}</span></p>
                <p class="product-meta">{html.escape(details)}</p>
                <p class="product-meta"><strong>{html.escape(tr("product_reason"))}:</strong> {html.escape(str(reason))}</p>
            </div>
            """
        )
        c1, c2, c3 = st.columns([1, 1, 1])
        qty = int(st.session_state["cart_quantities"].get(name, 1))
        if c1.button("-", key=f"minus_{name}", use_container_width=True, disabled=qty <= 0):
            next_qty = max(0, qty - 1)
            clear_order_state()
            st.session_state["cart_quantities"][name] = next_qty
            track_product_quantity_change(product, qty, next_qty, plan)
            st.rerun()
        c2.metric(tr("qty"), qty)
        if c3.button("+", key=f"plus_{name}", use_container_width=True):
            next_qty = qty + 1
            clear_order_state()
            st.session_state["cart_quantities"][name] = next_qty
            track_product_quantity_change(product, qty, next_qty, plan)
            st.rerun()

    subtotal, count = cart_totals(plan)
    delivery = 1.99 if count else 0
    total = subtotal + delivery
    st.metric(tr("subtotal"), money(subtotal))
    st.metric(tr("delivery"), money(delivery))
    st.metric(tr("total"), money(total))

    col1, col2 = st.columns(2)
    if col1.button(tr("clear_cart"), use_container_width=True):
        clear_order_state()
        for product in products:
            name = product.get("name", "")
            previous_qty = int(st.session_state["cart_quantities"].get(name, 0) or 0)
            st.session_state["cart_quantities"][name] = 0
            if previous_qty:
                track_product_quantity_change(product, previous_qty, 0, plan)
        track_event("cart_cleared", {}, plan)
        st.rerun()
    if col2.button(tr("reset_qty"), use_container_width=True):
        clear_order_state()
        for product in products:
            name = product.get("name", "")
            previous_qty = int(st.session_state["cart_quantities"].get(name, 0) or 0)
            st.session_state["cart_quantities"][name] = 1
            if previous_qty != 1:
                track_product_quantity_change(product, previous_qty, 1, plan)
        track_event("cart_reset", {}, plan)
        st.rerun()
    if st.button(tr("place_order"), type="primary", use_container_width=True, disabled=count <= 0):
        order_id = uuid.uuid4().hex
        track_event("checkout_started", {"mock_checkout": True, "order_id": order_id}, plan)
        track_order_line_items(plan, order_id)
        track_event("order_completed", {"mock_order": True, "order_id": order_id}, plan)
        st.session_state["last_mock_order"] = {
            "order_id": order_id,
            "item_count": count,
            "subtotal": subtotal,
            "delivery": delivery,
            "total": total,
            "items": cart_line_items(plan),
        }
        st.rerun()


def render_settings(runtime_config):
    st.subheader(tr("settings"))
    language_label = st.radio(
        tr("language"),
        list(LANGUAGE_OPTIONS.keys()),
        index=list(LANGUAGE_OPTIONS.values()).index(lang()),
        horizontal=True,
    )
    selected_lang = LANGUAGE_OPTIONS[language_label]
    if selected_lang != lang():
        st.session_state["language"] = selected_lang
        st.session_state["plan"] = None
        st.session_state["selected_recipe_index"] = 0
        st.session_state["business_goal"] = TEXT[selected_lang]["goal_options"][0]
        st.rerun()

    st.selectbox(tr("goal"), tr("goal_options"), key="business_goal")
    if runtime_config["ready"]:
        st.success(tr("model_ready"))
    else:
        st.warning(runtime_config["error"])


def render_admin():
    st.subheader(tr("admin_title"))
    st.caption(tr("admin_poc_only"))
    st.caption(tr("admin_window"))
    event_config = read_event_config()
    if not event_config["enabled"]:
        st.warning(tr("admin_disabled"))
        return

    if st.button(tr("admin_refresh"), use_container_width=True):
        fetch_admin_dashboard.clear()

    try:
        dashboard = fetch_admin_dashboard(
            event_config["project_id"],
            event_config["dataset"],
            event_config["table"],
        )
    except Exception as exc:
        logging.exception("Admin dashboard query failed")
        st.warning(f"{tr('admin_disabled')} ({exc})")
        return

    metrics = dashboard.get("metrics", {})
    event_count = int(metrics.get("event_count") or 0)
    if not event_count:
        st.info(tr("admin_empty"))
        return

    first_row = st.columns(3)
    first_row[0].metric(tr("admin_sessions"), int(metrics.get("session_count") or 0))
    first_row[1].metric(tr("admin_events"), event_count)
    first_row[2].metric(tr("admin_recipes"), int(metrics.get("recipe_count") or 0))

    second_row = st.columns(3)
    second_row[0].metric(tr("admin_recommendations"), int(metrics.get("product_recommendation_count") or 0))
    second_row[1].metric(tr("admin_orders"), int(metrics.get("order_count") or 0))
    second_row[2].metric(tr("admin_avg_cart"), money(metrics.get("avg_order_cart_subtotal") or 0))

    third_row = st.columns(2)
    third_row[0].metric(tr("admin_order_items"), int(metrics.get("order_line_item_count") or 0))
    third_row[1].metric(tr("admin_product_gmv"), money(metrics.get("product_mock_gmv") or 0))

    col1, col2 = st.columns(2)
    with col1:
        st.markdown(f"#### {tr('admin_top_ingredients')}")
        if dashboard.get("top_ingredients"):
            st.dataframe(dashboard["top_ingredients"], hide_index=True, use_container_width=True)
        else:
            st.caption(tr("admin_empty"))
    with col2:
        st.markdown(f"#### {tr('admin_top_products')}")
        if dashboard.get("top_products"):
            st.dataframe(dashboard["top_products"], hide_index=True, use_container_width=True)
        else:
            st.caption(tr("admin_empty"))

    st.markdown(f"#### {tr('admin_product_gmv')}")
    if dashboard.get("ordered_products"):
        st.dataframe(dashboard["ordered_products"], hide_index=True, use_container_width=True)
    else:
        st.caption(tr("admin_empty"))

    col3, col4 = st.columns(2)
    with col3:
        st.markdown(f"#### {tr('admin_promotion_performance')}")
        if dashboard.get("promotion_performance"):
            st.dataframe(dashboard["promotion_performance"], hide_index=True, use_container_width=True)
        else:
            st.caption(tr("admin_empty"))
    with col4:
        st.markdown(f"#### {tr('admin_model_performance')}")
        if dashboard.get("model_performance"):
            st.dataframe(dashboard["model_performance"], hide_index=True, use_container_width=True)
        else:
            st.caption(tr("admin_empty"))

    st.markdown(f"#### {tr('admin_recent_events')}")
    st.dataframe(dashboard.get("recent_events", []), hide_index=True, use_container_width=True)


def main():
    css()
    if "language" not in st.session_state:
        st.session_state["language"] = "en"
    if "ingredients" not in st.session_state:
        st.session_state["ingredients"] = []
    if "plan" not in st.session_state:
        st.session_state["plan"] = None
    if "cart_quantities" not in st.session_state:
        st.session_state["cart_quantities"] = {}
    if "manual_text" not in st.session_state:
        st.session_state["manual_text"] = ""
    if "business_goal" not in st.session_state:
        st.session_state["business_goal"] = tr("goal_options")[0]
    if "selected_recipe_index" not in st.session_state:
        st.session_state["selected_recipe_index"] = 0

    render_header()
    runtime_config = read_runtime_config()
    render_journey()

    scan_tab, ingredients_tab, recipe_tab, cart_tab, admin_tab, settings_tab = st.tabs(
        [tr("scan"), tr("ingredients"), tr("recipe"), tr("cart"), tr("admin"), tr("settings")]
    )

    with scan_tab:
        render_scan(runtime_config)
    with ingredients_tab:
        render_ingredients()
    with recipe_tab:
        render_recipe(runtime_config, st.session_state.get("business_goal", tr("goal_options")[0]))
    with cart_tab:
        render_cart()
    with admin_tab:
        render_admin()
    with settings_tab:
        render_settings(runtime_config)


main()
